In [170]:
!pip install pandas

import pandas as pd
import os
os.chdir(r"H:\&문체부 공모전&")
df=pd.read_csv("KOBIS_월별박스오피스_230506.csv")

Requirement already satisfied: pandas in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [171]:
df1 = df.iloc[7:568].reset_index(drop=True)
df1.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,범죄도시3,2023-05-31,"87,130,311,881",60.0%,"98,486,705,237","8,745,222","9,969,400","2,582","253,403",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
1,2,엘리멘탈,2023-06-14,"16,661,492,941",11.5%,"16,668,970,941","1,691,732","1,692,554","1,331","62,632",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,트랜스포머: 비스트의 서막,2023-06-06,"7,731,747,754",5.3%,"7,731,747,754","764,377","764,377","1,123","44,855",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
3,4,플래시,2023-06-14,"6,527,899,642",4.5%,"6,527,899,642","614,030","614,030","1,258","41,890",미국,미국,워너브러더스 코리아(주)
4,5,스파이더맨: 어크로스 더 유니버스,2023-06-21,"5,309,163,912",3.7%,"5,309,163,912","497,687","497,687","1,103","29,552",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점

In [172]:
df1.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
556,556,밀라노 두오모 콘서트,2022-01-07,0,0.0%,0,0,0,1,1,이탈리아,이탈리아,일미디어
557,556,육사오(6/45),2022-08-24,0,0.0%,"19,791,780,880",0,"1,980,856",1,1,한국,한국,"스튜디오 초이스 주식회사,(주)싸이더스"
558,556,애월,2019-09-26,0,0.0%,0,0,0,1,1,한국,한국,(주)드림팩트엔터테인먼트
559,556,시집가는 날,1957-02-11,0,0.0%,0,0,0,1,2,한국,한국,NaN
560,556,나의 결혼원정기,2005-11-23,0,0.0%,0,0,0,1,2,한국,한국,롯데쇼핑㈜롯데엔터테인먼트

In [175]:
df2 = df.iloc[578:-1].reset_index(drop=True)
df2.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠

In [176]:
df2.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
566,553,무화과나무 아래,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN
567,553,마콩고,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN
568,553,탈리야,NaN,0,0.0%,0,0,0,1,4,케냐,케냐,NaN
569,553,프레지던트,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN
570,553,2023 아프리카영화제: 소년들의 거짓말+가나단편선,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN

In [177]:
df1["month"]="23.06"
df1.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,month
0,1,범죄도시3,2023-05-31,"87,130,311,881",60.0%,"98,486,705,237","8,745,222","9,969,400","2,582","253,403",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.06
1,2,엘리멘탈,2023-06-14,"16,661,492,941",11.5%,"16,668,970,941","1,691,732","1,692,554","1,331","62,632",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.06
2,3,트랜스포머: 비스트의 서막,2023-06-06,"7,731,747,754",5.3%,"7,731,747,754","764,377","764,377","1,123","44,855",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.06
3,4,플래시,2023-06-14,"6,527,899,642",4.5%,"6,527,899,642","614,030","614,030","1,258","41,890",미국,미국,워너브러더스 코리아(주),23.06
4,5,스파이더맨: 어크로스 더 유니버스,2023-06-21,"5,309,163,912",3.7%,"5,309,163,912","497,687","497,687","1,103","29,552",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,23.06

In [178]:
df1.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df1.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,범죄도시3,2023-05-31,"87,130,311,881",60.0%,"98,486,705,237","8,745,222","9,969,400","2,582","253,403",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.06
1,2,엘리멘탈,2023-06-14,"16,661,492,941",11.5%,"16,668,970,941","1,691,732","1,692,554","1,331","62,632",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.06
2,3,트랜스포머: 비스트의 서막,2023-06-06,"7,731,747,754",5.3%,"7,731,747,754","764,377","764,377","1,123","44,855",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.06
3,4,플래시,2023-06-14,"6,527,899,642",4.5%,"6,527,899,642","614,030","614,030","1,258","41,890",미국,미국,워너브러더스 코리아(주),23.06
4,5,스파이더맨: 어크로스 더 유니버스,2023-06-21,"5,309,163,912",3.7%,"5,309,163,912","497,687","497,687","1,103","29,552",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,23.06

In [179]:
df2["month"]="23.05"
df2.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,month
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.05
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.05
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠,23.05

In [180]:
df2.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df2.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.05
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.05
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠,23.05

In [181]:
df = pd.concat([df2, df1])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.05
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.05
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠,23.05

In [182]:
df.to_csv("230506.csv", index=False)

In [61]:
df=pd.read_csv("KOBIS_월별박스오피스_230708.csv")
df3 = df.iloc[7:644].reset_index(drop=True)
df3.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,콘크리트 유토피아,2023-08-09,"33,729,838,362",23.5%,"33,754,618,362","3,452,681","3,454,857","1,731","110,766",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트
1,2,밀수,2023-07-26,"29,414,760,178",20.5%,"48,503,556,269","3,043,853","5,022,084","1,771","100,715",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
2,3,오펜하이머,2023-08-15,"26,923,397,740",18.8%,"26,923,397,740","2,525,885","2,525,885","1,636","79,345",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,엘리멘탈,2023-06-14,"12,526,218,715",8.7%,"69,421,734,462","1,285,652","7,065,124","1,019","48,897",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
4,5,비공식작전,2023-08-02,"9,760,586,384",6.8%,"10,170,842,196","1,013,010","1,056,202","1,151","44,657",한국,한국,(주)쇼박스

In [49]:
df3.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
632,619,에브리씽 에브리웨어 올 앳 원스+,2023-03-01,0,0.0%,0,0,0,1,1,미국,미국,워터홀컴퍼니(주)
633,619,"신수원 감독전: 레인보우부터 오마주,13년",NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
634,619,여자만세,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
635,619,제24회 대구단편영화제 대구단편신작전,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
636,619,기담,2007-08-01,0,0.0%,"4,142,762,500",0,"646,238",1,2,한국,한국,"(주)영화사오원,㈜스튜디오이쩜영"

In [63]:
df4 = df.iloc[649:-1].reset_index(drop=True)
df4.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,엘리멘탈,2023-06-14,"40,226,544,806",28.7%,"56,895,515,747","4,086,918","5,779,472","1,664","124,676",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,"36,264,590,140",25.9%,"36,264,590,140","3,594,887","3,594,887","2,437","121,203",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
2,3,밀수,2023-07-26,"19,088,796,091",13.6%,"19,088,796,091","1,978,231","1,978,231","1,932","54,142",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
3,4,범죄도시3,2023-05-31,"6,184,609,945",4.4%,"104,671,315,182","711,505","10,680,905",943,"42,706",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
4,5,인디아나 존스: 운명의 다이얼,2023-06-28,"6,239,832,155",4.5%,"8,501,034,347","618,807","860,174","1,268","34,242",미국,미국,월트디즈니컴퍼니코리아 유한책임회사

In [64]:
df4.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
524,514,애월,2019-09-26,0,0.0%,"11,763,360",0,"1,406",1,1,한국,한국,(주)드림팩트엔터테인먼트
525,514,그 섬에 가고 싶다,1993-12-24,0,0.0%,"221,000",0,43,1,1,한국,한국,NaN
526,514,축제,1996-06-06,0,0.0%,"217,000",0,30,1,1,한국,한국,NaN
527,514,학생부군신위,1996-03-01,0,0.0%,0,0,0,1,1,한국,한국,NaN
528,514,[뮤직&댄스 온 스크린] 댄스2,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN

In [65]:
df3["month"]="23.08"
df4["month"]="23.07"

In [66]:
df3.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df3.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,콘크리트 유토피아,2023-08-09,"33,729,838,362",23.5%,"33,754,618,362","3,452,681","3,454,857","1,731","110,766",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,23.08
1,2,밀수,2023-07-26,"29,414,760,178",20.5%,"48,503,556,269","3,043,853","5,022,084","1,771","100,715",한국,한국,(주)넥스트엔터테인먼트월드(NEW),23.08
2,3,오펜하이머,2023-08-15,"26,923,397,740",18.8%,"26,923,397,740","2,525,885","2,525,885","1,636","79,345",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.08
3,4,엘리멘탈,2023-06-14,"12,526,218,715",8.7%,"69,421,734,462","1,285,652","7,065,124","1,019","48,897",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.08
4,5,비공식작전,2023-08-02,"9,760,586,384",6.8%,"10,170,842,196","1,013,010","1,056,202","1,151","44,657",한국,한국,(주)쇼박스,23.08

In [67]:
df4.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df4.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,엘리멘탈,2023-06-14,"40,226,544,806",28.7%,"56,895,515,747","4,086,918","5,779,472","1,664","124,676",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07
1,2,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,"36,264,590,140",25.9%,"36,264,590,140","3,594,887","3,594,887","2,437","121,203",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.07
2,3,밀수,2023-07-26,"19,088,796,091",13.6%,"19,088,796,091","1,978,231","1,978,231","1,932","54,142",한국,한국,(주)넥스트엔터테인먼트월드(NEW),23.07
3,4,범죄도시3,2023-05-31,"6,184,609,945",4.4%,"104,671,315,182","711,505","10,680,905",943,"42,706",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.07
4,5,인디아나 존스: 운명의 다이얼,2023-06-28,"6,239,832,155",4.5%,"8,501,034,347","618,807","860,174","1,268","34,242",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07

In [68]:
df = pd.concat([df4, df3])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,엘리멘탈,2023-06-14,"40,226,544,806",28.7%,"56,895,515,747","4,086,918","5,779,472","1,664","124,676",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07
1,2,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,"36,264,590,140",25.9%,"36,264,590,140","3,594,887","3,594,887","2,437","121,203",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.07
2,3,밀수,2023-07-26,"19,088,796,091",13.6%,"19,088,796,091","1,978,231","1,978,231","1,932","54,142",한국,한국,(주)넥스트엔터테인먼트월드(NEW),23.07
3,4,범죄도시3,2023-05-31,"6,184,609,945",4.4%,"104,671,315,182","711,505","10,680,905",943,"42,706",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.07
4,5,인디아나 존스: 운명의 다이얼,2023-06-28,"6,239,832,155",4.5%,"8,501,034,347","618,807","860,174","1,268","34,242",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07

In [69]:
df.tail()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
632,619,에브리씽 에브리웨어 올 앳 원스+,2023-03-01,0,0.0%,0,0,0,1,1,미국,미국,워터홀컴퍼니(주),23.08
633,619,"신수원 감독전: 레인보우부터 오마주,13년",NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN,23.08
634,619,여자만세,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN,23.08
635,619,제24회 대구단편영화제 대구단편신작전,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN,23.08
636,619,기담,2007-08-01,0,0.0%,"4,142,762,500",0,"646,238",1,2,한국,한국,"(주)영화사오원,㈜스튜디오이쩜영",23.08

In [70]:
df.to_csv("230708.csv", index=False)

In [184]:
df=pd.read_csv("KOBIS_월별박스오피스_230910.csv")
df5 = df.iloc[7:709].reset_index(drop=True)
df5.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,30일,2023-10-03,"18,306,995,855",27.2%,"18,484,046,620","1,861,665","1,880,121","1,226","104,434",한국,한국,(주)마인드마크
1,2,그대들은 어떻게 살 것인가,2023-10-25,"10,325,060,680",15.3%,"10,325,060,680","1,063,664","1,063,664","1,733","47,081",일본,일본,메가박스중앙(주)
2,3,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,567,420,683",14.2%,"18,616,278,692","969,779","1,914,020","1,511","69,757",한국,한국,(주)씨제이이엔엠
3,4,1947 보스톤,2023-09-27,"4,805,311,432",7.1%,"9,207,227,580","529,880","991,277","1,282","41,639",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트"
4,5,크리에이터,2023-10-03,"2,701,136,233",4.0%,"2,765,702,233","255,753","261,773",878,"25,103",미국,미국,월트디즈니컴퍼니코리아 유한책임회사

In [185]:
df5.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
697,694,제9회 서울국제음식영화제 오감만족 국제단편경선 4,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN
698,694,시네마 퓨처,NaN,0,0.0%,0,0,0,1,1,오스트리아,오스트리아,NaN
699,694,니나 내나,2019-10-30,0,0.0%,0,0,0,1,1,한국,한국,(주)리틀빅픽쳐스
700,694,이소정 감독 단편선,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
701,694,오늘 출가합니다,2023-04-05,0,0.0%,0,0,0,1,1,한국,한국,(주)트리플픽쳐스

In [186]:
df6 = df.iloc[714:-1].reset_index(drop=True)
df6.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,잠,2023-09-06,"13,379,208,421",20.5%,"13,455,612,321","1,409,809","1,417,547","1,231","99,675",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트
1,2,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,048,858,009",13.9%,"9,048,858,009","944,241","944,241","1,502","28,843",한국,한국,(주)씨제이이엔엠
2,3,오펜하이머,2023-08-15,"7,124,568,890",10.9%,"34,047,966,630","676,425","3,202,310","1,158","50,884",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,1947 보스톤,2023-09-27,"4,401,916,148",6.7%,"4,401,916,148","461,397","461,397","1,273","20,165",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트"
4,5,달짝지근해: 7510,2023-08-15,"3,920,187,519",6.0%,"13,397,099,955","407,480","1,381,850",937,"39,989",한국,한국,(주)마인드마크

In [187]:
df6.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
770,747,운하의 다섯 스토리와 한 세기의 인생,NaN,0,0.0%,0,0,0,1,2,기타,기타,NaN
771,747,엘리스 & 톰,NaN,0,0.0%,0,0,0,1,2,브라질,브라질,NaN
772,747,길거리 환전소,NaN,0,0.0%,0,0,0,1,2,아르헨티나,아르헨티나,NaN
773,747,그 가족의 비밀,NaN,0,0.0%,0,0,0,1,2,페루,페루,NaN
774,747,제15회 서울영등포국제초단편영화제 글로벌 문화예술교육 2,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN

In [188]:
df5["month"]="23.10"
df6["month"]="23.09"

In [189]:
df5.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df5.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,30일,2023-10-03,"18,306,995,855",27.2%,"18,484,046,620","1,861,665","1,880,121","1,226","104,434",한국,한국,(주)마인드마크,23.10
1,2,그대들은 어떻게 살 것인가,2023-10-25,"10,325,060,680",15.3%,"10,325,060,680","1,063,664","1,063,664","1,733","47,081",일본,일본,메가박스중앙(주),23.10
2,3,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,567,420,683",14.2%,"18,616,278,692","969,779","1,914,020","1,511","69,757",한국,한국,(주)씨제이이엔엠,23.10
3,4,1947 보스톤,2023-09-27,"4,805,311,432",7.1%,"9,207,227,580","529,880","991,277","1,282","41,639",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트",23.10
4,5,크리에이터,2023-10-03,"2,701,136,233",4.0%,"2,765,702,233","255,753","261,773",878,"25,103",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.10

In [190]:
df6.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df6.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,잠,2023-09-06,"13,379,208,421",20.5%,"13,455,612,321","1,409,809","1,417,547","1,231","99,675",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,23.09
1,2,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,048,858,009",13.9%,"9,048,858,009","944,241","944,241","1,502","28,843",한국,한국,(주)씨제이이엔엠,23.09
2,3,오펜하이머,2023-08-15,"7,124,568,890",10.9%,"34,047,966,630","676,425","3,202,310","1,158","50,884",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.09
3,4,1947 보스톤,2023-09-27,"4,401,916,148",6.7%,"4,401,916,148","461,397","461,397","1,273","20,165",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트",23.09
4,5,달짝지근해: 7510,2023-08-15,"3,920,187,519",6.0%,"13,397,099,955","407,480","1,381,850",937,"39,989",한국,한국,(주)마인드마크,23.09

In [191]:
df = pd.concat([df6, df5])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,잠,2023-09-06,"13,379,208,421",20.5%,"13,455,612,321","1,409,809","1,417,547","1,231","99,675",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,23.09
1,2,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,048,858,009",13.9%,"9,048,858,009","944,241","944,241","1,502","28,843",한국,한국,(주)씨제이이엔엠,23.09
2,3,오펜하이머,2023-08-15,"7,124,568,890",10.9%,"34,047,966,630","676,425","3,202,310","1,158","50,884",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.09
3,4,1947 보스톤,2023-09-27,"4,401,916,148",6.7%,"4,401,916,148","461,397","461,397","1,273","20,165",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트",23.09
4,5,달짝지근해: 7510,2023-08-15,"3,920,187,519",6.0%,"13,397,099,955","407,480","1,381,850",937,"39,989",한국,한국,(주)마인드마크,23.09

In [192]:
df.to_csv("230910.csv", index=False)

In [91]:
df=pd.read_csv("KOBIS_월별박스오피스_231112.csv")

In [94]:
df7 = df.iloc[7:687].reset_index(drop=True)
df7.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,서울의 봄,2023-11-22,"87,680,455,951",53.4%,"115,350,491,410","8,901,879","11,854,779","2,463","215,008",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
1,2,노량: 죽음의 바다,2023-12-20,"34,032,608,940",20.7%,"34,032,608,940","3,438,133","3,438,133","2,196","81,643",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스"
2,3,아쿠아맨과 로스트 킹덤,2023-12-20,"7,459,599,772",4.5%,"7,459,599,772","722,986","722,986",965,"25,387",미국,미국,워너브러더스 코리아(주)
3,4,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,"5,506,327,689",3.4%,"5,506,327,689","568,269","568,269",883,"15,379",일본,일본,(주)씨제이이엔엠
4,5,3일의 휴가,2023-12-06,"4,808,376,689",2.9%,"4,835,070,689","511,659","514,541",863,"31,537",한국,한국,(주)쇼박스

In [95]:
df7.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
675,662,황진이,1986-09-18,0,0.0%,0,0,0,1,2,한국,한국,NaN
676,662,미워도 다시 한번,1968-07-16,0,0.0%,0,0,0,1,2,한국,한국,NaN
677,662,만추,1982-02-28,0,0.0%,0,0,0,1,2,한국,한국,NaN
678,662,태양의 서커스 월드 어웨이,2016-01-06,0,0.0%,0,0,0,1,1,미국,미국,주식회사 드림크리에이션
679,662,My Shooting Star - 이한주 배우전 단편전2,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN

In [97]:
df8 = df.iloc[692:-1].reset_index(drop=True)
df8.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,서울의 봄,2023-11-22,"27,670,035,459",37.8%,"27,670,035,459","2,952,900","2,952,900","2,328","77,291",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
1,2,그대들은 어떻게 살 것인가,2023-10-25,"8,858,746,363",12.1%,"19,183,807,043","903,085","1,966,749","1,343","69,594",일본,일본,메가박스중앙(주)
2,3,더 마블스,2023-11-08,"6,807,601,786",9.3%,"6,807,601,786","686,976","686,976","1,532","66,622",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
3,4,프레디의 피자가게,2023-11-15,"5,706,230,228",7.8%,"5,706,230,228","587,136","587,136","1,041","28,886",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
4,5,소년들,2023-11-01,"4,297,375,469",5.9%,"4,464,069,469","452,168","470,735","1,042","43,210",한국,한국,(주)씨제이이엔엠

In [98]:
df8.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
806,770,21번가의 살인자,NaN,0,0.0%,"1,267,000",0,241,1,1,프랑스,프랑스,NaN
807,770,찬실이는 복도 많지,2020-03-05,0,0.0%,"255,235,830",0,"29,900",1,1,한국,한국,찬란
808,770,서바이벌 택틱스,2024-02-21,0,0.0%,"559,000",0,70,1,1,한국,한국,필름다빈
809,770,씨앗의 시간,2024-11-20,0,0.0%,"449,000",0,64,1,1,한국,한국,필름다빈
810,770,2030 청년영화 2회 GV,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN

In [99]:
df7["month"]="23.12"
df8["month"]="23.11"

In [100]:
df7.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df7.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,서울의 봄,2023-11-22,"87,680,455,951",53.4%,"115,350,491,410","8,901,879","11,854,779","2,463","215,008",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,23.12
1,2,노량: 죽음의 바다,2023-12-20,"34,032,608,940",20.7%,"34,032,608,940","3,438,133","3,438,133","2,196","81,643",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스",23.12
2,3,아쿠아맨과 로스트 킹덤,2023-12-20,"7,459,599,772",4.5%,"7,459,599,772","722,986","722,986",965,"25,387",미국,미국,워너브러더스 코리아(주),23.12
3,4,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,"5,506,327,689",3.4%,"5,506,327,689","568,269","568,269",883,"15,379",일본,일본,(주)씨제이이엔엠,23.12
4,5,3일의 휴가,2023-12-06,"4,808,376,689",2.9%,"4,835,070,689","511,659","514,541",863,"31,537",한국,한국,(주)쇼박스,23.12

In [101]:
df8.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df8.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,서울의 봄,2023-11-22,"27,670,035,459",37.8%,"27,670,035,459","2,952,900","2,952,900","2,328","77,291",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,23.11
1,2,그대들은 어떻게 살 것인가,2023-10-25,"8,858,746,363",12.1%,"19,183,807,043","903,085","1,966,749","1,343","69,594",일본,일본,메가박스중앙(주),23.11
2,3,더 마블스,2023-11-08,"6,807,601,786",9.3%,"6,807,601,786","686,976","686,976","1,532","66,622",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.11
3,4,프레디의 피자가게,2023-11-15,"5,706,230,228",7.8%,"5,706,230,228","587,136","587,136","1,041","28,886",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.11
4,5,소년들,2023-11-01,"4,297,375,469",5.9%,"4,464,069,469","452,168","470,735","1,042","43,210",한국,한국,(주)씨제이이엔엠,23.11

In [103]:
df = pd.concat([df8, df7])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,서울의 봄,2023-11-22,"27,670,035,459",37.8%,"27,670,035,459","2,952,900","2,952,900","2,328","77,291",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,23.11
1,2,그대들은 어떻게 살 것인가,2023-10-25,"8,858,746,363",12.1%,"19,183,807,043","903,085","1,966,749","1,343","69,594",일본,일본,메가박스중앙(주),23.11
2,3,더 마블스,2023-11-08,"6,807,601,786",9.3%,"6,807,601,786","686,976","686,976","1,532","66,622",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.11
3,4,프레디의 피자가게,2023-11-15,"5,706,230,228",7.8%,"5,706,230,228","587,136","587,136","1,041","28,886",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.11
4,5,소년들,2023-11-01,"4,297,375,469",5.9%,"4,464,069,469","452,168","470,735","1,042","43,210",한국,한국,(주)씨제이이엔엠,23.11

In [104]:
df.to_csv("231112.csv", index=False)

In [105]:
df=pd.read_csv("KOBIS_월별박스오피스_240102.csv")

In [107]:
df9 = df.iloc[7:446].reset_index(drop=True)
df9.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,파묘,2024-02-22,"35,074,653,666",31.7%,"35,074,653,666","3,697,234","3,697,234","2,355","66,290",한국,한국,(주)쇼박스
1,2,웡카,2024-01-31,"28,559,191,141",25.8%,"30,068,563,086","2,943,396","3,124,697","1,753","124,701",미국,미국,워너브러더스 코리아(주)
2,3,시민덕희,2024-01-24,"9,958,903,001",9.0%,"16,075,976,297","1,038,452","1,700,935","1,281","58,090",한국,한국,(주)쇼박스
3,4,건국전쟁,2024-02-01,"9,619,732,158",8.7%,"9,637,314,158","1,031,011","1,032,762",956,"40,252",한국,한국,다큐스토리
4,5,"귀멸의 칼날: 인연의 기적, 그리고 합동 강화 훈련으로",2024-02-14,"4,901,269,600",4.4%,"4,901,269,600","426,871","426,871",393,"20,640",일본,일본,씨제이 씨지브이(CJ CGV)(주)

In [108]:
df9.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
434,434,영웅,2022-12-21,0,0.0%,0,0,0,1,1,한국,한국,(주)씨제이이엔엠
435,434,마이 제너레이션,2004-12-03,0,0.0%,0,0,0,1,2,한국,한국,아트플러스시네마네트워크
436,434,바이 준,1998-03-28,0,0.0%,0,0,0,1,2,한국,한국,NaN
437,434,고양이를 부탁해,2001-10-12,0,0.0%,0,0,0,1,2,한국,한국,"(주)엣나인필름,(주)시네마서비스"
438,434,나쁜 영화,1997-08-02,0,0.0%,0,0,0,1,2,한국,한국,대우시네마

In [115]:
df10 = df.iloc[451:-1].reset_index(drop=True)
df10.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,위시,2024-01-03,"12,946,267,193",17.3%,"12,956,605,193","1,356,390","1,357,472","1,421","83,743",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,외계+인 2부,2024-01-10,"13,016,779,919",17.4%,"13,016,779,919","1,349,620","1,349,620","1,390","89,503",한국,한국,(주)씨제이이엔엠
2,3,서울의 봄,2023-11-22,"11,970,794,644",16.0%,"127,321,286,054","1,206,194","13,060,973","1,614","75,922",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
3,4,노량: 죽음의 바다,2023-12-20,"10,854,904,560",14.5%,"44,887,513,500","1,122,234","4,560,367","1,706","72,225",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스"
4,5,시민덕희,2024-01-24,"6,117,073,296",8.2%,"6,117,073,296","662,483","662,483","1,272","37,916",한국,한국,(주)쇼박스

In [116]:
df10.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
484,483,파이란,2001-04-28,0,0.0%,"13,402,270",0,"1,380",1,2,한국,한국,"(주)영화사오원,(주)튜브엔터테인먼트"
485,483,해야 할 일,2024-09-25,0,0.0%,"4,020,000",0,510,1,1,한국,한국,재단법인 명필름문화재단
486,483,레전더리 콘서트: 레너드 번스타인,2021-01-03,0,0.0%,"13,413,500",0,519,1,1,독일,독일,(주)케빈앤컴퍼니
487,483,탑,2022-11-03,0,0.0%,"57,559,293",0,"6,134",1,1,한국,한국,"(주)영화제작전원사 ,(주)콘텐츠판다"
488,483,번지점프를 하다,2001-02-02,0,0.0%,"58,648,800",0,"7,248",1,2,한국,한국,"(주)넥스트엔터테인먼트월드(NEW),이언픽쳐스,브에나비스타인터내셔널코리아"

In [117]:
df9["month"]="24.02"
df10["month"]="24.01"

In [113]:
df9.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df9.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,파묘,2024-02-22,"35,074,653,666",31.7%,"35,074,653,666","3,697,234","3,697,234","2,355","66,290",한국,한국,(주)쇼박스,24.02
1,2,웡카,2024-01-31,"28,559,191,141",25.8%,"30,068,563,086","2,943,396","3,124,697","1,753","124,701",미국,미국,워너브러더스 코리아(주),24.02
2,3,시민덕희,2024-01-24,"9,958,903,001",9.0%,"16,075,976,297","1,038,452","1,700,935","1,281","58,090",한국,한국,(주)쇼박스,24.02
3,4,건국전쟁,2024-02-01,"9,619,732,158",8.7%,"9,637,314,158","1,031,011","1,032,762",956,"40,252",한국,한국,다큐스토리,24.02
4,5,"귀멸의 칼날: 인연의 기적, 그리고 합동 강화 훈련으로",2024-02-14,"4,901,269,600",4.4%,"4,901,269,600","426,871","426,871",393,"20,640",일본,일본,씨제이 씨지브이(CJ CGV)(주),24.02

In [118]:
df10.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df10.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,위시,2024-01-03,"12,946,267,193",17.3%,"12,956,605,193","1,356,390","1,357,472","1,421","83,743",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.01
1,2,외계+인 2부,2024-01-10,"13,016,779,919",17.4%,"13,016,779,919","1,349,620","1,349,620","1,390","89,503",한국,한국,(주)씨제이이엔엠,24.01
2,3,서울의 봄,2023-11-22,"11,970,794,644",16.0%,"127,321,286,054","1,206,194","13,060,973","1,614","75,922",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.01
3,4,노량: 죽음의 바다,2023-12-20,"10,854,904,560",14.5%,"44,887,513,500","1,122,234","4,560,367","1,706","72,225",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스",24.01
4,5,시민덕희,2024-01-24,"6,117,073,296",8.2%,"6,117,073,296","662,483","662,483","1,272","37,916",한국,한국,(주)쇼박스,24.01

In [119]:
df = pd.concat([df10, df9])

In [120]:
df.to_csv("240102.csv", index=False)

In [121]:
df=pd.read_csv("KOBIS_월별박스오피스_240304.csv")

In [126]:
df11 = df.iloc[7:542].reset_index(drop=True)
df11.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,범죄도시4,2024-04-24,"47,568,478,254",52.9%,"47,568,478,254","5,005,372","5,005,372","2,980","112,858",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
1,2,쿵푸팬더4,2024-04-10,"13,113,276,904",14.6%,"13,124,943,904","1,403,363","1,404,570","2,311","90,797",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
2,3,파묘,2024-02-22,"8,837,982,638",9.8%,"114,631,306,846","902,841","11,860,132","1,280","76,395",한국,한국,(주)쇼박스
3,4,댓글부대,2024-03-27,"4,185,464,098",4.7%,"9,227,726,211","430,033","971,080","1,059","43,303",한국,한국,(주)에이스메이커무비웍스
4,5,남은 인생 10년,2023-05-24,"2,862,042,165",3.2%,"2,862,042,165","287,554","287,554",529,"18,821",일본,일본,"(주)바이포엠스튜디오,(주)디스테이션"

In [127]:
df11.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
530,526,비공식작전,2023-08-02,0,0.0%,0,0,0,1,1,한국,한국,(주)쇼박스
531,526,그녀를 믿지 마세요,2004-02-20,0,0.0%,0,0,0,1,2,한국,한국,(주)시네마서비스
532,526,범죄의 재구성,2004-04-15,0,0.0%,0,0,0,1,2,한국,한국,(주)쇼박스
533,526,타짜,2006-09-28,0,0.0%,0,0,0,1,2,한국,한국,씨제이엔터테인먼트
534,526,찬실이는 복도 많지,2020-03-05,0,0.0%,0,0,0,1,1,한국,한국,찬란

In [130]:
df12 = df.iloc[547:-1].reset_index(drop=True)
df12.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,파묘,2024-02-22,"70,718,670,542",60.7%,"105,793,324,208","7,260,057","10,957,291","2,367","218,130",한국,한국,(주)쇼박스
1,2,듄: 파트2,2024-02-28,"19,142,164,349",16.4%,"21,941,132,462","1,617,518","1,886,023","1,190","65,973",미국,미국,워너브러더스 코리아(주)
2,3,댓글부대,2024-03-27,"5,042,262,113",4.3%,"5,042,262,113","541,047","541,047","1,228","24,274",한국,한국,(주)에이스메이커무비웍스
3,4,웡카,2024-01-31,"3,838,072,524",3.3%,"33,906,635,610","401,512","3,526,209",695,"19,507",미국,미국,워너브러더스 코리아(주)
4,5,고질라 X 콩: 뉴 엠파이어,2024-03-27,"3,221,961,514",2.8%,"3,221,961,514","321,128","321,128",995,"16,323",미국,미국,워너브러더스 코리아(주)

In [131]:
df11["month"]="24.04"
df12["month"]="24.03"

In [132]:
df11.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df11.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,범죄도시4,2024-04-24,"47,568,478,254",52.9%,"47,568,478,254","5,005,372","5,005,372","2,980","112,858",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",24.04
1,2,쿵푸팬더4,2024-04-10,"13,113,276,904",14.6%,"13,124,943,904","1,403,363","1,404,570","2,311","90,797",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.04
2,3,파묘,2024-02-22,"8,837,982,638",9.8%,"114,631,306,846","902,841","11,860,132","1,280","76,395",한국,한국,(주)쇼박스,24.04
3,4,댓글부대,2024-03-27,"4,185,464,098",4.7%,"9,227,726,211","430,033","971,080","1,059","43,303",한국,한국,(주)에이스메이커무비웍스,24.04
4,5,남은 인생 10년,2023-05-24,"2,862,042,165",3.2%,"2,862,042,165","287,554","287,554",529,"18,821",일본,일본,"(주)바이포엠스튜디오,(주)디스테이션",24.04

In [133]:
df12.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df12.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,파묘,2024-02-22,"70,718,670,542",60.7%,"105,793,324,208","7,260,057","10,957,291","2,367","218,130",한국,한국,(주)쇼박스,24.03
1,2,듄: 파트2,2024-02-28,"19,142,164,349",16.4%,"21,941,132,462","1,617,518","1,886,023","1,190","65,973",미국,미국,워너브러더스 코리아(주),24.03
2,3,댓글부대,2024-03-27,"5,042,262,113",4.3%,"5,042,262,113","541,047","541,047","1,228","24,274",한국,한국,(주)에이스메이커무비웍스,24.03
3,4,웡카,2024-01-31,"3,838,072,524",3.3%,"33,906,635,610","401,512","3,526,209",695,"19,507",미국,미국,워너브러더스 코리아(주),24.03
4,5,고질라 X 콩: 뉴 엠파이어,2024-03-27,"3,221,961,514",2.8%,"3,221,961,514","321,128","321,128",995,"16,323",미국,미국,워너브러더스 코리아(주),24.03

In [134]:
df = pd.concat([df12, df11])

In [135]:
df.to_csv("240304.csv", index=False)

In [136]:
df=pd.read_csv("KOBIS_월별박스오피스_240506.csv")

In [145]:
df13 = df.iloc[7:649].reset_index(drop=True)
df13.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,인사이드 아웃 2,2024-06-12,"54,296,410,494",49.9%,"54,296,410,494","5,638,833","5,638,833","2,619","191,541",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,하이재킹,2024-06-21,"10,314,943,018",9.5%,"10,316,869,018","1,087,330","1,087,544","1,155","41,879",한국,한국,"소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,(주)키다리스튜디오"
2,3,퓨리오사: 매드맥스 사가,2024-05-22,"7,986,194,948",7.3%,"16,420,562,828","786,121","1,598,473","1,360","48,082",미국,미국,워너브러더스 코리아(주)
3,4,원더랜드,2024-06-05,"5,857,952,571",5.4%,"5,898,947,571","618,867","623,338","1,165","43,764",한국,한국,(주)에이스메이커무비웍스
4,5,핸섬가이즈,2024-06-26,"4,224,677,026",3.9%,"4,226,900,026","458,626","458,873",965,"18,195",한국,한국,(주)넥스트엔터테인먼트월드(NEW)

In [146]:
df13.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
637,627,임신한 나무와 도깨비,2022-01-27,0,0.0%,0,0,0,1,1,한국,한국,(주)시네마달
638,627,세계의 이미지와 전쟁의 각인,NaN,0,0.0%,0,0,0,1,1,독일,독일,NaN
639,627,짝코,1983-10-23,0,0.0%,0,0,0,1,2,한국,한국,NaN
640,627,송환,2004-03-19,0,0.0%,0,0,0,1,2,한국,한국,㈜인디스토리
641,627,땡큐 포 더 레인,NaN,0,0.0%,0,0,0,1,1,케냐,케냐,NaN

In [152]:
df14 = df.iloc[654:-1].reset_index(drop=True)
df14.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,범죄도시4,2024-04-24,"59,331,646,657",54.1%,"106,900,124,911","6,174,857","11,180,229","2,795","237,235",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
1,2,혹성탈출: 새로운 시대,2024-05-08,"8,983,534,876",8.2%,"8,983,534,876","887,475","887,475","1,184","51,514",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,그녀가 죽었다,2024-05-15,"7,991,507,015",7.3%,"7,995,476,015","837,143","837,584","1,008","48,245",한국,한국,"(주)콘텐츠지오,(주)아티스트스튜디오,(주)무빙픽쳐스컴퍼니"
3,4,퓨리오사: 매드맥스 사가,2024-05-22,"8,434,367,880",7.7%,"8,434,367,880","812,352","812,352","1,442","44,871",미국,미국,워너브러더스 코리아(주)
4,5,극장판 하이큐!! 쓰레기장의 결전,2024-05-15,"5,529,154,607",5.0%,"5,529,154,607","536,130","536,130","1,212","32,913",일본,일본,"(주)넥스트엔터테인먼트월드(NEW),씨제이 씨지브이(CJ CGV)(주)"

In [153]:
df14.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
573,557,성냥팔이 소녀의 재림,2002-09-12,0,0.0%,0,0,0,1,2,한국,한국,씨제이엔터테인먼트
574,557,파산의 기술,NaN,0,0.0%,"504,000",0,74,1,1,한국,한국,NaN
575,557,만다라,1981-09-12,0,0.0%,"2,568,000",0,934,1,2,한국,한국,NaN
576,557,달마가 동쪽으로 간 까닭은?,1989-09-29,0,0.0%,0,0,0,1,2,한국,한국,NaN
577,557,마카리오,NaN,0,0.0%,0,0,0,NaN,1,멕시코,멕시코,NaN

In [154]:
df13["month"]="24.06"
df14["month"]="24.05"

In [155]:
df13.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df13.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,인사이드 아웃 2,2024-06-12,"54,296,410,494",49.9%,"54,296,410,494","5,638,833","5,638,833","2,619","191,541",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.06
1,2,하이재킹,2024-06-21,"10,314,943,018",9.5%,"10,316,869,018","1,087,330","1,087,544","1,155","41,879",한국,한국,"소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,(주)키다리스튜디오",24.06
2,3,퓨리오사: 매드맥스 사가,2024-05-22,"7,986,194,948",7.3%,"16,420,562,828","786,121","1,598,473","1,360","48,082",미국,미국,워너브러더스 코리아(주),24.06
3,4,원더랜드,2024-06-05,"5,857,952,571",5.4%,"5,898,947,571","618,867","623,338","1,165","43,764",한국,한국,(주)에이스메이커무비웍스,24.06
4,5,핸섬가이즈,2024-06-26,"4,224,677,026",3.9%,"4,226,900,026","458,626","458,873",965,"18,195",한국,한국,(주)넥스트엔터테인먼트월드(NEW),24.06

In [156]:
df14.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df14.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,범죄도시4,2024-04-24,"59,331,646,657",54.1%,"106,900,124,911","6,174,857","11,180,229","2,795","237,235",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",24.05
1,2,혹성탈출: 새로운 시대,2024-05-08,"8,983,534,876",8.2%,"8,983,534,876","887,475","887,475","1,184","51,514",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.05
2,3,그녀가 죽었다,2024-05-15,"7,991,507,015",7.3%,"7,995,476,015","837,143","837,584","1,008","48,245",한국,한국,"(주)콘텐츠지오,(주)아티스트스튜디오,(주)무빙픽쳐스컴퍼니",24.05
3,4,퓨리오사: 매드맥스 사가,2024-05-22,"8,434,367,880",7.7%,"8,434,367,880","812,352","812,352","1,442","44,871",미국,미국,워너브러더스 코리아(주),24.05
4,5,극장판 하이큐!! 쓰레기장의 결전,2024-05-15,"5,529,154,607",5.0%,"5,529,154,607","536,130","536,130","1,212","32,913",일본,일본,"(주)넥스트엔터테인먼트월드(NEW),씨제이 씨지브이(CJ CGV)(주)",24.05

In [157]:
df = pd.concat([df14, df13])

In [159]:
df.head()
df.to_csv("240506.csv", index=False)