In [170]:
!pip install pandas

import pandas as pd
import os
os.chdir(r"H:\&문체부 공모전&")
df=pd.read_csv("KOBIS_월별박스오피스_230506.csv")

Requirement already satisfied: pandas in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\jac11\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [171]:
df1 = df.iloc[7:568].reset_index(drop=True)
df1.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,범죄도시3,2023-05-31,"87,130,311,881",60.0%,"98,486,705,237","8,745,222","9,969,400","2,582","253,403",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
1,2,엘리멘탈,2023-06-14,"16,661,492,941",11.5%,"16,668,970,941","1,691,732","1,692,554","1,331","62,632",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,트랜스포머: 비스트의 서막,2023-06-06,"7,731,747,754",5.3%,"7,731,747,754","764,377","764,377","1,123","44,855",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
3,4,플래시,2023-06-14,"6,527,899,642",4.5%,"6,527,899,642","614,030","614,030","1,258","41,890",미국,미국,워너브러더스 코리아(주)
4,5,스파이더맨: 어크로스 더 유니버스,2023-06-21,"5,309,163,912",3.7%,"5,309,163,912","497,687","497,687","1,103","29,552",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점

In [172]:
df1.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
556,556,밀라노 두오모 콘서트,2022-01-07,0,0.0%,0,0,0,1,1,이탈리아,이탈리아,일미디어
557,556,육사오(6/45),2022-08-24,0,0.0%,"19,791,780,880",0,"1,980,856",1,1,한국,한국,"스튜디오 초이스 주식회사,(주)싸이더스"
558,556,애월,2019-09-26,0,0.0%,0,0,0,1,1,한국,한국,(주)드림팩트엔터테인먼트
559,556,시집가는 날,1957-02-11,0,0.0%,0,0,0,1,2,한국,한국,NaN
560,556,나의 결혼원정기,2005-11-23,0,0.0%,0,0,0,1,2,한국,한국,롯데쇼핑㈜롯데엔터테인먼트

In [175]:
df2 = df.iloc[578:-1].reset_index(drop=True)
df2.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠

In [176]:
df2.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
566,553,무화과나무 아래,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN
567,553,마콩고,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN
568,553,탈리야,NaN,0,0.0%,0,0,0,1,4,케냐,케냐,NaN
569,553,프레지던트,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN
570,553,2023 아프리카영화제: 소년들의 거짓말+가나단편선,NaN,0,0.0%,0,0,0,1,4,기타,기타,NaN

In [177]:
df1["month"]="23.06"
df1.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,month
0,1,범죄도시3,2023-05-31,"87,130,311,881",60.0%,"98,486,705,237","8,745,222","9,969,400","2,582","253,403",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.06
1,2,엘리멘탈,2023-06-14,"16,661,492,941",11.5%,"16,668,970,941","1,691,732","1,692,554","1,331","62,632",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.06
2,3,트랜스포머: 비스트의 서막,2023-06-06,"7,731,747,754",5.3%,"7,731,747,754","764,377","764,377","1,123","44,855",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.06
3,4,플래시,2023-06-14,"6,527,899,642",4.5%,"6,527,899,642","614,030","614,030","1,258","41,890",미국,미국,워너브러더스 코리아(주),23.06
4,5,스파이더맨: 어크로스 더 유니버스,2023-06-21,"5,309,163,912",3.7%,"5,309,163,912","497,687","497,687","1,103","29,552",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,23.06

In [178]:
df1.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df1.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,범죄도시3,2023-05-31,"87,130,311,881",60.0%,"98,486,705,237","8,745,222","9,969,400","2,582","253,403",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.06
1,2,엘리멘탈,2023-06-14,"16,661,492,941",11.5%,"16,668,970,941","1,691,732","1,692,554","1,331","62,632",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.06
2,3,트랜스포머: 비스트의 서막,2023-06-06,"7,731,747,754",5.3%,"7,731,747,754","764,377","764,377","1,123","44,855",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.06
3,4,플래시,2023-06-14,"6,527,899,642",4.5%,"6,527,899,642","614,030","614,030","1,258","41,890",미국,미국,워너브러더스 코리아(주),23.06
4,5,스파이더맨: 어크로스 더 유니버스,2023-06-21,"5,309,163,912",3.7%,"5,309,163,912","497,687","497,687","1,103","29,552",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,23.06

In [179]:
df2["month"]="23.05"
df2.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,month
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.05
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.05
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠,23.05

In [180]:
df2.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df2.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.05
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.05
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠,23.05

In [181]:
df = pd.concat([df2, df1])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,가디언즈 오브 갤럭시: Volume 3,2023-05-03,"41,558,564,678",35.0%,"41,558,564,678","3,936,452","3,936,452","1,819","139,717",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.05
1,2,분노의 질주: 라이드 오어 다이,2023-05-17,"16,994,798,760",14.3%,"16,994,798,760","1,624,933","1,624,933","1,731","82,524",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
2,3,슈퍼 마리오 브라더스,2023-04-26,"15,203,394,429",12.8%,"22,924,703,237","1,559,739","2,328,838","1,576","60,940",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.05
3,4,범죄도시3,2023-05-31,"11,356,393,356",9.6%,"11,356,393,356","1,224,178","1,224,178","2,352","15,487",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.05
4,5,극장판 짱구는 못말려: 동물소환 닌자 배꼽수비대,2023-05-04,"6,793,684,949",5.7%,"6,831,105,825","685,661","688,746",844,"26,670",일본,일본,(주)씨제이이엔엠,23.05

In [182]:
df.to_csv("230506.csv", index=False)

In [61]:
df=pd.read_csv("KOBIS_월별박스오피스_230708.csv")
df3 = df.iloc[7:644].reset_index(drop=True)
df3.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,콘크리트 유토피아,2023-08-09,"33,729,838,362",23.5%,"33,754,618,362","3,452,681","3,454,857","1,731","110,766",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트
1,2,밀수,2023-07-26,"29,414,760,178",20.5%,"48,503,556,269","3,043,853","5,022,084","1,771","100,715",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
2,3,오펜하이머,2023-08-15,"26,923,397,740",18.8%,"26,923,397,740","2,525,885","2,525,885","1,636","79,345",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,엘리멘탈,2023-06-14,"12,526,218,715",8.7%,"69,421,734,462","1,285,652","7,065,124","1,019","48,897",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
4,5,비공식작전,2023-08-02,"9,760,586,384",6.8%,"10,170,842,196","1,013,010","1,056,202","1,151","44,657",한국,한국,(주)쇼박스

In [49]:
df3.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
632,619,에브리씽 에브리웨어 올 앳 원스+,2023-03-01,0,0.0%,0,0,0,1,1,미국,미국,워터홀컴퍼니(주)
633,619,"신수원 감독전: 레인보우부터 오마주,13년",NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
634,619,여자만세,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
635,619,제24회 대구단편영화제 대구단편신작전,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
636,619,기담,2007-08-01,0,0.0%,"4,142,762,500",0,"646,238",1,2,한국,한국,"(주)영화사오원,㈜스튜디오이쩜영"

In [63]:
df4 = df.iloc[649:-1].reset_index(drop=True)
df4.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,엘리멘탈,2023-06-14,"40,226,544,806",28.7%,"56,895,515,747","4,086,918","5,779,472","1,664","124,676",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,"36,264,590,140",25.9%,"36,264,590,140","3,594,887","3,594,887","2,437","121,203",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
2,3,밀수,2023-07-26,"19,088,796,091",13.6%,"19,088,796,091","1,978,231","1,978,231","1,932","54,142",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
3,4,범죄도시3,2023-05-31,"6,184,609,945",4.4%,"104,671,315,182","711,505","10,680,905",943,"42,706",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
4,5,인디아나 존스: 운명의 다이얼,2023-06-28,"6,239,832,155",4.5%,"8,501,034,347","618,807","860,174","1,268","34,242",미국,미국,월트디즈니컴퍼니코리아 유한책임회사

In [64]:
df4.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
524,514,애월,2019-09-26,0,0.0%,"11,763,360",0,"1,406",1,1,한국,한국,(주)드림팩트엔터테인먼트
525,514,그 섬에 가고 싶다,1993-12-24,0,0.0%,"221,000",0,43,1,1,한국,한국,NaN
526,514,축제,1996-06-06,0,0.0%,"217,000",0,30,1,1,한국,한국,NaN
527,514,학생부군신위,1996-03-01,0,0.0%,0,0,0,1,1,한국,한국,NaN
528,514,[뮤직&댄스 온 스크린] 댄스2,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN

In [65]:
df3["month"]="23.08"
df4["month"]="23.07"

In [66]:
df3.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df3.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,콘크리트 유토피아,2023-08-09,"33,729,838,362",23.5%,"33,754,618,362","3,452,681","3,454,857","1,731","110,766",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,23.08
1,2,밀수,2023-07-26,"29,414,760,178",20.5%,"48,503,556,269","3,043,853","5,022,084","1,771","100,715",한국,한국,(주)넥스트엔터테인먼트월드(NEW),23.08
2,3,오펜하이머,2023-08-15,"26,923,397,740",18.8%,"26,923,397,740","2,525,885","2,525,885","1,636","79,345",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.08
3,4,엘리멘탈,2023-06-14,"12,526,218,715",8.7%,"69,421,734,462","1,285,652","7,065,124","1,019","48,897",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.08
4,5,비공식작전,2023-08-02,"9,760,586,384",6.8%,"10,170,842,196","1,013,010","1,056,202","1,151","44,657",한국,한국,(주)쇼박스,23.08

In [67]:
df4.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df4.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,엘리멘탈,2023-06-14,"40,226,544,806",28.7%,"56,895,515,747","4,086,918","5,779,472","1,664","124,676",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07
1,2,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,"36,264,590,140",25.9%,"36,264,590,140","3,594,887","3,594,887","2,437","121,203",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.07
2,3,밀수,2023-07-26,"19,088,796,091",13.6%,"19,088,796,091","1,978,231","1,978,231","1,932","54,142",한국,한국,(주)넥스트엔터테인먼트월드(NEW),23.07
3,4,범죄도시3,2023-05-31,"6,184,609,945",4.4%,"104,671,315,182","711,505","10,680,905",943,"42,706",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.07
4,5,인디아나 존스: 운명의 다이얼,2023-06-28,"6,239,832,155",4.5%,"8,501,034,347","618,807","860,174","1,268","34,242",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07

In [68]:
df = pd.concat([df4, df3])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,엘리멘탈,2023-06-14,"40,226,544,806",28.7%,"56,895,515,747","4,086,918","5,779,472","1,664","124,676",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07
1,2,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,"36,264,590,140",25.9%,"36,264,590,140","3,594,887","3,594,887","2,437","121,203",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,23.07
2,3,밀수,2023-07-26,"19,088,796,091",13.6%,"19,088,796,091","1,978,231","1,978,231","1,932","54,142",한국,한국,(주)넥스트엔터테인먼트월드(NEW),23.07
3,4,범죄도시3,2023-05-31,"6,184,609,945",4.4%,"104,671,315,182","711,505","10,680,905",943,"42,706",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",23.07
4,5,인디아나 존스: 운명의 다이얼,2023-06-28,"6,239,832,155",4.5%,"8,501,034,347","618,807","860,174","1,268","34,242",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.07

In [69]:
df.tail()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
632,619,에브리씽 에브리웨어 올 앳 원스+,2023-03-01,0,0.0%,0,0,0,1,1,미국,미국,워터홀컴퍼니(주),23.08
633,619,"신수원 감독전: 레인보우부터 오마주,13년",NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN,23.08
634,619,여자만세,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN,23.08
635,619,제24회 대구단편영화제 대구단편신작전,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN,23.08
636,619,기담,2007-08-01,0,0.0%,"4,142,762,500",0,"646,238",1,2,한국,한국,"(주)영화사오원,㈜스튜디오이쩜영",23.08

In [70]:
df.to_csv("230708.csv", index=False)

In [184]:
df=pd.read_csv("KOBIS_월별박스오피스_230910.csv")
df5 = df.iloc[7:709].reset_index(drop=True)
df5.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,30일,2023-10-03,"18,306,995,855",27.2%,"18,484,046,620","1,861,665","1,880,121","1,226","104,434",한국,한국,(주)마인드마크
1,2,그대들은 어떻게 살 것인가,2023-10-25,"10,325,060,680",15.3%,"10,325,060,680","1,063,664","1,063,664","1,733","47,081",일본,일본,메가박스중앙(주)
2,3,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,567,420,683",14.2%,"18,616,278,692","969,779","1,914,020","1,511","69,757",한국,한국,(주)씨제이이엔엠
3,4,1947 보스톤,2023-09-27,"4,805,311,432",7.1%,"9,207,227,580","529,880","991,277","1,282","41,639",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트"
4,5,크리에이터,2023-10-03,"2,701,136,233",4.0%,"2,765,702,233","255,753","261,773",878,"25,103",미국,미국,월트디즈니컴퍼니코리아 유한책임회사

In [185]:
df5.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
697,694,제9회 서울국제음식영화제 오감만족 국제단편경선 4,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN
698,694,시네마 퓨처,NaN,0,0.0%,0,0,0,1,1,오스트리아,오스트리아,NaN
699,694,니나 내나,2019-10-30,0,0.0%,0,0,0,1,1,한국,한국,(주)리틀빅픽쳐스
700,694,이소정 감독 단편선,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
701,694,오늘 출가합니다,2023-04-05,0,0.0%,0,0,0,1,1,한국,한국,(주)트리플픽쳐스

In [186]:
df6 = df.iloc[714:-1].reset_index(drop=True)
df6.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,잠,2023-09-06,"13,379,208,421",20.5%,"13,455,612,321","1,409,809","1,417,547","1,231","99,675",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트
1,2,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,048,858,009",13.9%,"9,048,858,009","944,241","944,241","1,502","28,843",한국,한국,(주)씨제이이엔엠
2,3,오펜하이머,2023-08-15,"7,124,568,890",10.9%,"34,047,966,630","676,425","3,202,310","1,158","50,884",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,1947 보스톤,2023-09-27,"4,401,916,148",6.7%,"4,401,916,148","461,397","461,397","1,273","20,165",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트"
4,5,달짝지근해: 7510,2023-08-15,"3,920,187,519",6.0%,"13,397,099,955","407,480","1,381,850",937,"39,989",한국,한국,(주)마인드마크

In [187]:
df6.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
770,747,운하의 다섯 스토리와 한 세기의 인생,NaN,0,0.0%,0,0,0,1,2,기타,기타,NaN
771,747,엘리스 & 톰,NaN,0,0.0%,0,0,0,1,2,브라질,브라질,NaN
772,747,길거리 환전소,NaN,0,0.0%,0,0,0,1,2,아르헨티나,아르헨티나,NaN
773,747,그 가족의 비밀,NaN,0,0.0%,0,0,0,1,2,페루,페루,NaN
774,747,제15회 서울영등포국제초단편영화제 글로벌 문화예술교육 2,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN

In [188]:
df5["month"]="23.10"
df6["month"]="23.09"

In [189]:
df5.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df5.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,30일,2023-10-03,"18,306,995,855",27.2%,"18,484,046,620","1,861,665","1,880,121","1,226","104,434",한국,한국,(주)마인드마크,23.10
1,2,그대들은 어떻게 살 것인가,2023-10-25,"10,325,060,680",15.3%,"10,325,060,680","1,063,664","1,063,664","1,733","47,081",일본,일본,메가박스중앙(주),23.10
2,3,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,567,420,683",14.2%,"18,616,278,692","969,779","1,914,020","1,511","69,757",한국,한국,(주)씨제이이엔엠,23.10
3,4,1947 보스톤,2023-09-27,"4,805,311,432",7.1%,"9,207,227,580","529,880","991,277","1,282","41,639",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트",23.10
4,5,크리에이터,2023-10-03,"2,701,136,233",4.0%,"2,765,702,233","255,753","261,773",878,"25,103",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.10

In [190]:
df6.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df6.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,잠,2023-09-06,"13,379,208,421",20.5%,"13,455,612,321","1,409,809","1,417,547","1,231","99,675",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,23.09
1,2,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,048,858,009",13.9%,"9,048,858,009","944,241","944,241","1,502","28,843",한국,한국,(주)씨제이이엔엠,23.09
2,3,오펜하이머,2023-08-15,"7,124,568,890",10.9%,"34,047,966,630","676,425","3,202,310","1,158","50,884",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.09
3,4,1947 보스톤,2023-09-27,"4,401,916,148",6.7%,"4,401,916,148","461,397","461,397","1,273","20,165",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트",23.09
4,5,달짝지근해: 7510,2023-08-15,"3,920,187,519",6.0%,"13,397,099,955","407,480","1,381,850",937,"39,989",한국,한국,(주)마인드마크,23.09

In [191]:
df = pd.concat([df6, df5])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,잠,2023-09-06,"13,379,208,421",20.5%,"13,455,612,321","1,409,809","1,417,547","1,231","99,675",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,23.09
1,2,천박사 퇴마 연구소: 설경의 비밀,2023-09-27,"9,048,858,009",13.9%,"9,048,858,009","944,241","944,241","1,502","28,843",한국,한국,(주)씨제이이엔엠,23.09
2,3,오펜하이머,2023-08-15,"7,124,568,890",10.9%,"34,047,966,630","676,425","3,202,310","1,158","50,884",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.09
3,4,1947 보스톤,2023-09-27,"4,401,916,148",6.7%,"4,401,916,148","461,397","461,397","1,273","20,165",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)콘텐츠지오,주식회사 에이투지엔터테인먼트",23.09
4,5,달짝지근해: 7510,2023-08-15,"3,920,187,519",6.0%,"13,397,099,955","407,480","1,381,850",937,"39,989",한국,한국,(주)마인드마크,23.09

In [192]:
df.to_csv("230910.csv", index=False)

In [91]:
df=pd.read_csv("KOBIS_월별박스오피스_231112.csv")

In [94]:
df7 = df.iloc[7:687].reset_index(drop=True)
df7.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,서울의 봄,2023-11-22,"87,680,455,951",53.4%,"115,350,491,410","8,901,879","11,854,779","2,463","215,008",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
1,2,노량: 죽음의 바다,2023-12-20,"34,032,608,940",20.7%,"34,032,608,940","3,438,133","3,438,133","2,196","81,643",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스"
2,3,아쿠아맨과 로스트 킹덤,2023-12-20,"7,459,599,772",4.5%,"7,459,599,772","722,986","722,986",965,"25,387",미국,미국,워너브러더스 코리아(주)
3,4,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,"5,506,327,689",3.4%,"5,506,327,689","568,269","568,269",883,"15,379",일본,일본,(주)씨제이이엔엠
4,5,3일의 휴가,2023-12-06,"4,808,376,689",2.9%,"4,835,070,689","511,659","514,541",863,"31,537",한국,한국,(주)쇼박스

In [95]:
df7.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
675,662,황진이,1986-09-18,0,0.0%,0,0,0,1,2,한국,한국,NaN
676,662,미워도 다시 한번,1968-07-16,0,0.0%,0,0,0,1,2,한국,한국,NaN
677,662,만추,1982-02-28,0,0.0%,0,0,0,1,2,한국,한국,NaN
678,662,태양의 서커스 월드 어웨이,2016-01-06,0,0.0%,0,0,0,1,1,미국,미국,주식회사 드림크리에이션
679,662,My Shooting Star - 이한주 배우전 단편전2,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN

In [97]:
df8 = df.iloc[692:-1].reset_index(drop=True)
df8.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,서울의 봄,2023-11-22,"27,670,035,459",37.8%,"27,670,035,459","2,952,900","2,952,900","2,328","77,291",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
1,2,그대들은 어떻게 살 것인가,2023-10-25,"8,858,746,363",12.1%,"19,183,807,043","903,085","1,966,749","1,343","69,594",일본,일본,메가박스중앙(주)
2,3,더 마블스,2023-11-08,"6,807,601,786",9.3%,"6,807,601,786","686,976","686,976","1,532","66,622",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
3,4,프레디의 피자가게,2023-11-15,"5,706,230,228",7.8%,"5,706,230,228","587,136","587,136","1,041","28,886",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
4,5,소년들,2023-11-01,"4,297,375,469",5.9%,"4,464,069,469","452,168","470,735","1,042","43,210",한국,한국,(주)씨제이이엔엠

In [98]:
df8.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
806,770,21번가의 살인자,NaN,0,0.0%,"1,267,000",0,241,1,1,프랑스,프랑스,NaN
807,770,찬실이는 복도 많지,2020-03-05,0,0.0%,"255,235,830",0,"29,900",1,1,한국,한국,찬란
808,770,서바이벌 택틱스,2024-02-21,0,0.0%,"559,000",0,70,1,1,한국,한국,필름다빈
809,770,씨앗의 시간,2024-11-20,0,0.0%,"449,000",0,64,1,1,한국,한국,필름다빈
810,770,2030 청년영화 2회 GV,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN

In [99]:
df7["month"]="23.12"
df8["month"]="23.11"

In [100]:
df7.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df7.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,서울의 봄,2023-11-22,"87,680,455,951",53.4%,"115,350,491,410","8,901,879","11,854,779","2,463","215,008",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,23.12
1,2,노량: 죽음의 바다,2023-12-20,"34,032,608,940",20.7%,"34,032,608,940","3,438,133","3,438,133","2,196","81,643",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스",23.12
2,3,아쿠아맨과 로스트 킹덤,2023-12-20,"7,459,599,772",4.5%,"7,459,599,772","722,986","722,986",965,"25,387",미국,미국,워너브러더스 코리아(주),23.12
3,4,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,"5,506,327,689",3.4%,"5,506,327,689","568,269","568,269",883,"15,379",일본,일본,(주)씨제이이엔엠,23.12
4,5,3일의 휴가,2023-12-06,"4,808,376,689",2.9%,"4,835,070,689","511,659","514,541",863,"31,537",한국,한국,(주)쇼박스,23.12

In [101]:
df8.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df8.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,서울의 봄,2023-11-22,"27,670,035,459",37.8%,"27,670,035,459","2,952,900","2,952,900","2,328","77,291",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,23.11
1,2,그대들은 어떻게 살 것인가,2023-10-25,"8,858,746,363",12.1%,"19,183,807,043","903,085","1,966,749","1,343","69,594",일본,일본,메가박스중앙(주),23.11
2,3,더 마블스,2023-11-08,"6,807,601,786",9.3%,"6,807,601,786","686,976","686,976","1,532","66,622",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.11
3,4,프레디의 피자가게,2023-11-15,"5,706,230,228",7.8%,"5,706,230,228","587,136","587,136","1,041","28,886",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.11
4,5,소년들,2023-11-01,"4,297,375,469",5.9%,"4,464,069,469","452,168","470,735","1,042","43,210",한국,한국,(주)씨제이이엔엠,23.11

In [103]:
df = pd.concat([df8, df7])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,서울의 봄,2023-11-22,"27,670,035,459",37.8%,"27,670,035,459","2,952,900","2,952,900","2,328","77,291",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,23.11
1,2,그대들은 어떻게 살 것인가,2023-10-25,"8,858,746,363",12.1%,"19,183,807,043","903,085","1,966,749","1,343","69,594",일본,일본,메가박스중앙(주),23.11
2,3,더 마블스,2023-11-08,"6,807,601,786",9.3%,"6,807,601,786","686,976","686,976","1,532","66,622",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,23.11
3,4,프레디의 피자가게,2023-11-15,"5,706,230,228",7.8%,"5,706,230,228","587,136","587,136","1,041","28,886",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),23.11
4,5,소년들,2023-11-01,"4,297,375,469",5.9%,"4,464,069,469","452,168","470,735","1,042","43,210",한국,한국,(주)씨제이이엔엠,23.11

In [104]:
df.to_csv("231112.csv", index=False)

In [105]:
df=pd.read_csv("KOBIS_월별박스오피스_240102.csv")

In [107]:
df9 = df.iloc[7:446].reset_index(drop=True)
df9.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,파묘,2024-02-22,"35,074,653,666",31.7%,"35,074,653,666","3,697,234","3,697,234","2,355","66,290",한국,한국,(주)쇼박스
1,2,웡카,2024-01-31,"28,559,191,141",25.8%,"30,068,563,086","2,943,396","3,124,697","1,753","124,701",미국,미국,워너브러더스 코리아(주)
2,3,시민덕희,2024-01-24,"9,958,903,001",9.0%,"16,075,976,297","1,038,452","1,700,935","1,281","58,090",한국,한국,(주)쇼박스
3,4,건국전쟁,2024-02-01,"9,619,732,158",8.7%,"9,637,314,158","1,031,011","1,032,762",956,"40,252",한국,한국,다큐스토리
4,5,"귀멸의 칼날: 인연의 기적, 그리고 합동 강화 훈련으로",2024-02-14,"4,901,269,600",4.4%,"4,901,269,600","426,871","426,871",393,"20,640",일본,일본,씨제이 씨지브이(CJ CGV)(주)

In [108]:
df9.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
434,434,영웅,2022-12-21,0,0.0%,0,0,0,1,1,한국,한국,(주)씨제이이엔엠
435,434,마이 제너레이션,2004-12-03,0,0.0%,0,0,0,1,2,한국,한국,아트플러스시네마네트워크
436,434,바이 준,1998-03-28,0,0.0%,0,0,0,1,2,한국,한국,NaN
437,434,고양이를 부탁해,2001-10-12,0,0.0%,0,0,0,1,2,한국,한국,"(주)엣나인필름,(주)시네마서비스"
438,434,나쁜 영화,1997-08-02,0,0.0%,0,0,0,1,2,한국,한국,대우시네마

In [115]:
df10 = df.iloc[451:-1].reset_index(drop=True)
df10.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,위시,2024-01-03,"12,946,267,193",17.3%,"12,956,605,193","1,356,390","1,357,472","1,421","83,743",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,외계+인 2부,2024-01-10,"13,016,779,919",17.4%,"13,016,779,919","1,349,620","1,349,620","1,390","89,503",한국,한국,(주)씨제이이엔엠
2,3,서울의 봄,2023-11-22,"11,970,794,644",16.0%,"127,321,286,054","1,206,194","13,060,973","1,614","75,922",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
3,4,노량: 죽음의 바다,2023-12-20,"10,854,904,560",14.5%,"44,887,513,500","1,122,234","4,560,367","1,706","72,225",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스"
4,5,시민덕희,2024-01-24,"6,117,073,296",8.2%,"6,117,073,296","662,483","662,483","1,272","37,916",한국,한국,(주)쇼박스

In [116]:
df10.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
484,483,파이란,2001-04-28,0,0.0%,"13,402,270",0,"1,380",1,2,한국,한국,"(주)영화사오원,(주)튜브엔터테인먼트"
485,483,해야 할 일,2024-09-25,0,0.0%,"4,020,000",0,510,1,1,한국,한국,재단법인 명필름문화재단
486,483,레전더리 콘서트: 레너드 번스타인,2021-01-03,0,0.0%,"13,413,500",0,519,1,1,독일,독일,(주)케빈앤컴퍼니
487,483,탑,2022-11-03,0,0.0%,"57,559,293",0,"6,134",1,1,한국,한국,"(주)영화제작전원사 ,(주)콘텐츠판다"
488,483,번지점프를 하다,2001-02-02,0,0.0%,"58,648,800",0,"7,248",1,2,한국,한국,"(주)넥스트엔터테인먼트월드(NEW),이언픽쳐스,브에나비스타인터내셔널코리아"

In [117]:
df9["month"]="24.02"
df10["month"]="24.01"

In [113]:
df9.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df9.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,파묘,2024-02-22,"35,074,653,666",31.7%,"35,074,653,666","3,697,234","3,697,234","2,355","66,290",한국,한국,(주)쇼박스,24.02
1,2,웡카,2024-01-31,"28,559,191,141",25.8%,"30,068,563,086","2,943,396","3,124,697","1,753","124,701",미국,미국,워너브러더스 코리아(주),24.02
2,3,시민덕희,2024-01-24,"9,958,903,001",9.0%,"16,075,976,297","1,038,452","1,700,935","1,281","58,090",한국,한국,(주)쇼박스,24.02
3,4,건국전쟁,2024-02-01,"9,619,732,158",8.7%,"9,637,314,158","1,031,011","1,032,762",956,"40,252",한국,한국,다큐스토리,24.02
4,5,"귀멸의 칼날: 인연의 기적, 그리고 합동 강화 훈련으로",2024-02-14,"4,901,269,600",4.4%,"4,901,269,600","426,871","426,871",393,"20,640",일본,일본,씨제이 씨지브이(CJ CGV)(주),24.02

In [118]:
df10.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df10.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,위시,2024-01-03,"12,946,267,193",17.3%,"12,956,605,193","1,356,390","1,357,472","1,421","83,743",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.01
1,2,외계+인 2부,2024-01-10,"13,016,779,919",17.4%,"13,016,779,919","1,349,620","1,349,620","1,390","89,503",한국,한국,(주)씨제이이엔엠,24.01
2,3,서울의 봄,2023-11-22,"11,970,794,644",16.0%,"127,321,286,054","1,206,194","13,060,973","1,614","75,922",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.01
3,4,노량: 죽음의 바다,2023-12-20,"10,854,904,560",14.5%,"44,887,513,500","1,122,234","4,560,367","1,706","72,225",한국,한국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)에이스메이커무비웍스",24.01
4,5,시민덕희,2024-01-24,"6,117,073,296",8.2%,"6,117,073,296","662,483","662,483","1,272","37,916",한국,한국,(주)쇼박스,24.01

In [119]:
df = pd.concat([df10, df9])

In [120]:
df.to_csv("240102.csv", index=False)

In [121]:
df=pd.read_csv("KOBIS_월별박스오피스_240304.csv")

In [126]:
df11 = df.iloc[7:542].reset_index(drop=True)
df11.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,범죄도시4,2024-04-24,"47,568,478,254",52.9%,"47,568,478,254","5,005,372","5,005,372","2,980","112,858",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
1,2,쿵푸팬더4,2024-04-10,"13,113,276,904",14.6%,"13,124,943,904","1,403,363","1,404,570","2,311","90,797",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
2,3,파묘,2024-02-22,"8,837,982,638",9.8%,"114,631,306,846","902,841","11,860,132","1,280","76,395",한국,한국,(주)쇼박스
3,4,댓글부대,2024-03-27,"4,185,464,098",4.7%,"9,227,726,211","430,033","971,080","1,059","43,303",한국,한국,(주)에이스메이커무비웍스
4,5,남은 인생 10년,2023-05-24,"2,862,042,165",3.2%,"2,862,042,165","287,554","287,554",529,"18,821",일본,일본,"(주)바이포엠스튜디오,(주)디스테이션"

In [127]:
df11.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
530,526,비공식작전,2023-08-02,0,0.0%,0,0,0,1,1,한국,한국,(주)쇼박스
531,526,그녀를 믿지 마세요,2004-02-20,0,0.0%,0,0,0,1,2,한국,한국,(주)시네마서비스
532,526,범죄의 재구성,2004-04-15,0,0.0%,0,0,0,1,2,한국,한국,(주)쇼박스
533,526,타짜,2006-09-28,0,0.0%,0,0,0,1,2,한국,한국,씨제이엔터테인먼트
534,526,찬실이는 복도 많지,2020-03-05,0,0.0%,0,0,0,1,1,한국,한국,찬란

In [130]:
df12 = df.iloc[547:-1].reset_index(drop=True)
df12.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,파묘,2024-02-22,"70,718,670,542",60.7%,"105,793,324,208","7,260,057","10,957,291","2,367","218,130",한국,한국,(주)쇼박스
1,2,듄: 파트2,2024-02-28,"19,142,164,349",16.4%,"21,941,132,462","1,617,518","1,886,023","1,190","65,973",미국,미국,워너브러더스 코리아(주)
2,3,댓글부대,2024-03-27,"5,042,262,113",4.3%,"5,042,262,113","541,047","541,047","1,228","24,274",한국,한국,(주)에이스메이커무비웍스
3,4,웡카,2024-01-31,"3,838,072,524",3.3%,"33,906,635,610","401,512","3,526,209",695,"19,507",미국,미국,워너브러더스 코리아(주)
4,5,고질라 X 콩: 뉴 엠파이어,2024-03-27,"3,221,961,514",2.8%,"3,221,961,514","321,128","321,128",995,"16,323",미국,미국,워너브러더스 코리아(주)

In [131]:
df11["month"]="24.04"
df12["month"]="24.03"

In [132]:
df11.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df11.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,범죄도시4,2024-04-24,"47,568,478,254",52.9%,"47,568,478,254","5,005,372","5,005,372","2,980","112,858",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",24.04
1,2,쿵푸팬더4,2024-04-10,"13,113,276,904",14.6%,"13,124,943,904","1,403,363","1,404,570","2,311","90,797",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.04
2,3,파묘,2024-02-22,"8,837,982,638",9.8%,"114,631,306,846","902,841","11,860,132","1,280","76,395",한국,한국,(주)쇼박스,24.04
3,4,댓글부대,2024-03-27,"4,185,464,098",4.7%,"9,227,726,211","430,033","971,080","1,059","43,303",한국,한국,(주)에이스메이커무비웍스,24.04
4,5,남은 인생 10년,2023-05-24,"2,862,042,165",3.2%,"2,862,042,165","287,554","287,554",529,"18,821",일본,일본,"(주)바이포엠스튜디오,(주)디스테이션",24.04

In [133]:
df12.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df12.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,파묘,2024-02-22,"70,718,670,542",60.7%,"105,793,324,208","7,260,057","10,957,291","2,367","218,130",한국,한국,(주)쇼박스,24.03
1,2,듄: 파트2,2024-02-28,"19,142,164,349",16.4%,"21,941,132,462","1,617,518","1,886,023","1,190","65,973",미국,미국,워너브러더스 코리아(주),24.03
2,3,댓글부대,2024-03-27,"5,042,262,113",4.3%,"5,042,262,113","541,047","541,047","1,228","24,274",한국,한국,(주)에이스메이커무비웍스,24.03
3,4,웡카,2024-01-31,"3,838,072,524",3.3%,"33,906,635,610","401,512","3,526,209",695,"19,507",미국,미국,워너브러더스 코리아(주),24.03
4,5,고질라 X 콩: 뉴 엠파이어,2024-03-27,"3,221,961,514",2.8%,"3,221,961,514","321,128","321,128",995,"16,323",미국,미국,워너브러더스 코리아(주),24.03

In [134]:
df = pd.concat([df12, df11])

In [135]:
df.to_csv("240304.csv", index=False)

In [136]:
df=pd.read_csv("KOBIS_월별박스오피스_240506.csv")

In [145]:
df13 = df.iloc[7:649].reset_index(drop=True)
df13.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,인사이드 아웃 2,2024-06-12,"54,296,410,494",49.9%,"54,296,410,494","5,638,833","5,638,833","2,619","191,541",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,하이재킹,2024-06-21,"10,314,943,018",9.5%,"10,316,869,018","1,087,330","1,087,544","1,155","41,879",한국,한국,"소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,(주)키다리스튜디오"
2,3,퓨리오사: 매드맥스 사가,2024-05-22,"7,986,194,948",7.3%,"16,420,562,828","786,121","1,598,473","1,360","48,082",미국,미국,워너브러더스 코리아(주)
3,4,원더랜드,2024-06-05,"5,857,952,571",5.4%,"5,898,947,571","618,867","623,338","1,165","43,764",한국,한국,(주)에이스메이커무비웍스
4,5,핸섬가이즈,2024-06-26,"4,224,677,026",3.9%,"4,226,900,026","458,626","458,873",965,"18,195",한국,한국,(주)넥스트엔터테인먼트월드(NEW)

In [146]:
df13.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
637,627,임신한 나무와 도깨비,2022-01-27,0,0.0%,0,0,0,1,1,한국,한국,(주)시네마달
638,627,세계의 이미지와 전쟁의 각인,NaN,0,0.0%,0,0,0,1,1,독일,독일,NaN
639,627,짝코,1983-10-23,0,0.0%,0,0,0,1,2,한국,한국,NaN
640,627,송환,2004-03-19,0,0.0%,0,0,0,1,2,한국,한국,㈜인디스토리
641,627,땡큐 포 더 레인,NaN,0,0.0%,0,0,0,1,1,케냐,케냐,NaN

In [152]:
df14 = df.iloc[654:-1].reset_index(drop=True)
df14.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,범죄도시4,2024-04-24,"59,331,646,657",54.1%,"106,900,124,911","6,174,857","11,180,229","2,795","237,235",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트"
1,2,혹성탈출: 새로운 시대,2024-05-08,"8,983,534,876",8.2%,"8,983,534,876","887,475","887,475","1,184","51,514",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,그녀가 죽었다,2024-05-15,"7,991,507,015",7.3%,"7,995,476,015","837,143","837,584","1,008","48,245",한국,한국,"(주)콘텐츠지오,(주)아티스트스튜디오,(주)무빙픽쳐스컴퍼니"
3,4,퓨리오사: 매드맥스 사가,2024-05-22,"8,434,367,880",7.7%,"8,434,367,880","812,352","812,352","1,442","44,871",미국,미국,워너브러더스 코리아(주)
4,5,극장판 하이큐!! 쓰레기장의 결전,2024-05-15,"5,529,154,607",5.0%,"5,529,154,607","536,130","536,130","1,212","32,913",일본,일본,"(주)넥스트엔터테인먼트월드(NEW),씨제이 씨지브이(CJ CGV)(주)"

In [153]:
df14.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
573,557,성냥팔이 소녀의 재림,2002-09-12,0,0.0%,0,0,0,1,2,한국,한국,씨제이엔터테인먼트
574,557,파산의 기술,NaN,0,0.0%,"504,000",0,74,1,1,한국,한국,NaN
575,557,만다라,1981-09-12,0,0.0%,"2,568,000",0,934,1,2,한국,한국,NaN
576,557,달마가 동쪽으로 간 까닭은?,1989-09-29,0,0.0%,0,0,0,1,2,한국,한국,NaN
577,557,마카리오,NaN,0,0.0%,0,0,0,NaN,1,멕시코,멕시코,NaN

In [154]:
df13["month"]="24.06"
df14["month"]="24.05"

In [155]:
df13.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df13.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,인사이드 아웃 2,2024-06-12,"54,296,410,494",49.9%,"54,296,410,494","5,638,833","5,638,833","2,619","191,541",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.06
1,2,하이재킹,2024-06-21,"10,314,943,018",9.5%,"10,316,869,018","1,087,330","1,087,544","1,155","41,879",한국,한국,"소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,(주)키다리스튜디오",24.06
2,3,퓨리오사: 매드맥스 사가,2024-05-22,"7,986,194,948",7.3%,"16,420,562,828","786,121","1,598,473","1,360","48,082",미국,미국,워너브러더스 코리아(주),24.06
3,4,원더랜드,2024-06-05,"5,857,952,571",5.4%,"5,898,947,571","618,867","623,338","1,165","43,764",한국,한국,(주)에이스메이커무비웍스,24.06
4,5,핸섬가이즈,2024-06-26,"4,224,677,026",3.9%,"4,226,900,026","458,626","458,873",965,"18,195",한국,한국,(주)넥스트엔터테인먼트월드(NEW),24.06

In [156]:
df14.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df14.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,범죄도시4,2024-04-24,"59,331,646,657",54.1%,"106,900,124,911","6,174,857","11,180,229","2,795","237,235",한국,한국,"주식회사 에이비오엔터테인먼트,메가박스중앙(주) 플러스엠 엔터테인먼트",24.05
1,2,혹성탈출: 새로운 시대,2024-05-08,"8,983,534,876",8.2%,"8,983,534,876","887,475","887,475","1,184","51,514",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.05
2,3,그녀가 죽었다,2024-05-15,"7,991,507,015",7.3%,"7,995,476,015","837,143","837,584","1,008","48,245",한국,한국,"(주)콘텐츠지오,(주)아티스트스튜디오,(주)무빙픽쳐스컴퍼니",24.05
3,4,퓨리오사: 매드맥스 사가,2024-05-22,"8,434,367,880",7.7%,"8,434,367,880","812,352","812,352","1,442","44,871",미국,미국,워너브러더스 코리아(주),24.05
4,5,극장판 하이큐!! 쓰레기장의 결전,2024-05-15,"5,529,154,607",5.0%,"5,529,154,607","536,130","536,130","1,212","32,913",일본,일본,"(주)넥스트엔터테인먼트월드(NEW),씨제이 씨지브이(CJ CGV)(주)",24.05

In [157]:
df = pd.concat([df14, df13])

In [159]:
df.head()
df.to_csv("240506.csv", index=False)

In [2]:

import pandas as pd
import os
os.chdir(r"H:\&문체부 공모전&")

df=pd.read_csv("KOBIS_월별박스오피스_240708.csv")

In [7]:
df15 = df.iloc[7:752].reset_index(drop=True)
df15.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,파일럿,2024-07-31,"37,622,232,042",32.2%,"41,070,640,861","4,032,634","4,457,939","1,956","169,009",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트
1,2,에이리언: 로물루스,2024-08-14,"16,004,583,339",13.7%,"16,004,583,339","1,560,130","1,560,130","1,436","66,005",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,사랑의 하츄핑,2024-08-07,"7,549,787,272",6.5%,"7,679,896,522","838,138","849,826","1,159","37,437",한국,한국,(주)쇼박스
3,4,슈퍼배드 4,2024-07-24,"6,397,596,976",5.5%,"14,083,082,100","704,730","1,548,560","1,110","35,852",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
4,5,행복의 나라,2024-08-14,"6,299,715,896",5.4%,"6,302,599,896","681,438","681,731","1,096","42,676",한국,한국,(주)넥스트엔터테인먼트월드(NEW)

In [8]:
df15.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
740,730,AM I FUNNY?,NaN,0,0.0%,0,0,0,1,2,기타,기타,NaN
741,730,사랑은 고양이처럼,NaN,0,0.0%,0,0,0,1,1,한국,"한국,태국",NaN
742,730,"지금, 오아시스",NaN,0,0.0%,0,0,0,1,1,말레이시아,"말레이시아,싱가포르,프랑스",NaN
743,730,솔리드 바이 더 씨,NaN,0,0.0%,0,0,0,1,1,태국,태국,NaN
744,730,두 개의 문,2012-06-21,0,0.0%,0,0,0,1,2,한국,한국,(주)시네마달

In [11]:
df16 = df.iloc[757:-1].reset_index(drop=True)
df16.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,인사이드 아웃 2,2024-06-12,"26,472,253,172",23.0%,"80,768,663,666","2,767,299","8,406,132","1,664","120,555",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,탈주,2024-07-03,"22,537,334,282",19.5%,"22,665,054,282","2,382,788","2,396,691","1,234","108,501",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
2,3,데드풀과 울버린,2024-07-24,"13,839,704,940",12.0%,"13,839,704,940","1,352,113","1,352,113","1,948","60,958",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
3,4,핸섬가이즈,2024-06-26,"12,116,866,192",10.5%,"16,343,766,218","1,289,849","1,748,722","1,065","73,126",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
4,5,슈퍼배드 4,2024-07-24,"7,685,485,124",6.7%,"7,685,485,124","843,830","843,830","1,178","36,541",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)

In [12]:
df16.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
603,598,"아리랑시네센터X이경미, 잘돼가?무엇이든",NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
604,598,필름다빈X아리랑인디웨이브 섹션1,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
605,598,필름다빈X아리랑인디웨이브 섹션 2,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
606,598,하녀,1960-11-03,0,0.0%,"42,812,000",0,"10,559",1,2,한국,한국,NaN
607,608,블리츠,2011-12-07,"-6,000",0.0%,"-6,000",-3,-3,NaN,3,영국,영국,팝엔터테인먼트

In [13]:
df15["month"]="24.08"
df16["month"]="24.07"

In [14]:
df15.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df15.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,파일럿,2024-07-31,"37,622,232,042",32.2%,"41,070,640,861","4,032,634","4,457,939","1,956","169,009",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,24.08
1,2,에이리언: 로물루스,2024-08-14,"16,004,583,339",13.7%,"16,004,583,339","1,560,130","1,560,130","1,436","66,005",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.08
2,3,사랑의 하츄핑,2024-08-07,"7,549,787,272",6.5%,"7,679,896,522","838,138","849,826","1,159","37,437",한국,한국,(주)쇼박스,24.08
3,4,슈퍼배드 4,2024-07-24,"6,397,596,976",5.5%,"14,083,082,100","704,730","1,548,560","1,110","35,852",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.08
4,5,행복의 나라,2024-08-14,"6,299,715,896",5.4%,"6,302,599,896","681,438","681,731","1,096","42,676",한국,한국,(주)넥스트엔터테인먼트월드(NEW),24.08

In [15]:
df16.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df16.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,인사이드 아웃 2,2024-06-12,"26,472,253,172",23.0%,"80,768,663,666","2,767,299","8,406,132","1,664","120,555",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.07
1,2,탈주,2024-07-03,"22,537,334,282",19.5%,"22,665,054,282","2,382,788","2,396,691","1,234","108,501",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.07
2,3,데드풀과 울버린,2024-07-24,"13,839,704,940",12.0%,"13,839,704,940","1,352,113","1,352,113","1,948","60,958",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.07
3,4,핸섬가이즈,2024-06-26,"12,116,866,192",10.5%,"16,343,766,218","1,289,849","1,748,722","1,065","73,126",한국,한국,(주)넥스트엔터테인먼트월드(NEW),24.07
4,5,슈퍼배드 4,2024-07-24,"7,685,485,124",6.7%,"7,685,485,124","843,830","843,830","1,178","36,541",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.07

In [16]:
df = pd.concat([df16, df15])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,인사이드 아웃 2,2024-06-12,"26,472,253,172",23.0%,"80,768,663,666","2,767,299","8,406,132","1,664","120,555",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.07
1,2,탈주,2024-07-03,"22,537,334,282",19.5%,"22,665,054,282","2,382,788","2,396,691","1,234","108,501",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.07
2,3,데드풀과 울버린,2024-07-24,"13,839,704,940",12.0%,"13,839,704,940","1,352,113","1,352,113","1,948","60,958",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.07
3,4,핸섬가이즈,2024-06-26,"12,116,866,192",10.5%,"16,343,766,218","1,289,849","1,748,722","1,065","73,126",한국,한국,(주)넥스트엔터테인먼트월드(NEW),24.07
4,5,슈퍼배드 4,2024-07-24,"7,685,485,124",6.7%,"7,685,485,124","843,830","843,830","1,178","36,541",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.07

In [17]:
df.to_csv("240708.csv", index=False)

In [32]:
df=pd.read_csv("KOBIS_월별박스오피스_240910.csv")

In [33]:
df17 = df.iloc[7:650].reset_index(drop=True)
df17.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,베테랑2,2024-09-13,"9,870,120,218",16.1%,"72,367,797,714","1,024,813","7,514,196","1,317","77,127",한국,한국,(주)씨제이이엔엠
1,2,베놈: 라스트 댄스,2024-10-23,"9,847,662,388",16.0%,"9,847,662,388","1,005,411","1,005,411","1,663","59,063",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
2,3,대도시의 사랑법,2024-10-01,"7,297,350,650",11.9%,"7,385,538,550","774,053","783,106","1,101","65,414",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
3,4,조커: 폴리 아 되,2024-10-01,"6,366,573,920",10.4%,"6,377,181,920","611,371","611,995","1,385","45,742",미국,미국,워너브러더스 코리아(주)
4,5,와일드 로봇,2024-10-01,"5,391,693,670",8.8%,"5,502,661,670","595,334","606,448","1,062","42,261",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)

In [34]:
df17.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
638,612,살시뿌에데스,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN
639,612,The Night Won’t End,NaN,0,0.0%,0,0,0,1,1,카타르,카타르,NaN
640,612,대구청춘스펙트럼영화제 - 단편섹션,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
641,612,구름이 그림자를 숨길 때,NaN,0,0.0%,0,0,0,1,2,칠레,"칠레,아르헨티나,한국",NaN
642,612,회오리 바람,2010-02-25,0,0.0%,0,0,0,1,1,한국,한국,(주)영화사 진진

In [36]:
df18 = df.iloc[655:-1].reset_index(drop=True)
df18.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,베테랑2,2024-09-13,"62,497,677,496",62.4%,"62,497,677,496","6,489,383","6,489,383","2,691","200,561",한국,한국,(주)씨제이이엔엠
1,2,에이리언: 로물루스,2024-08-14,"4,400,663,791",4.4%,"20,405,247,130","438,500","1,998,630","1,009","41,535",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,사랑의 하츄핑,2024-08-07,"2,596,577,910",2.6%,"10,276,474,432","297,701","1,147,527",690,"14,411",한국,한국,(주)쇼박스
3,4,"안녕, 할부지",2024-09-04,"2,281,541,639",2.3%,"2,317,495,639","246,581","250,528","1,021","28,065",한국,한국,(주)바른손이앤에이
4,5,파일럿,2024-07-31,"2,020,981,840",2.0%,"43,091,622,701","244,276","4,702,215",840,"25,057",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트

In [37]:
df18.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
701,689,판타지아전 섹션3,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
702,689,차별없이 억압없이 배제없이 혐오없이,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
703,689,제 16회 서울국제건축영화제 호스트 아키텍트 포럼,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN
704,689,바얌섬,2025-10-29,0,0.0%,0,0,0,1,1,한국,한국,필름다빈
705,689,애국소녀,NaN,0,0.0%,"2,809,000",0,343,1,1,한국,한국,NaN

In [42]:
df17["month"]="24.10"
df18["month"]="24.09"

In [43]:
df17.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df17.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,베테랑2,2024-09-13,"9,870,120,218",16.1%,"72,367,797,714","1,024,813","7,514,196","1,317","77,127",한국,한국,(주)씨제이이엔엠,24.10
1,2,베놈: 라스트 댄스,2024-10-23,"9,847,662,388",16.0%,"9,847,662,388","1,005,411","1,005,411","1,663","59,063",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,24.10
2,3,대도시의 사랑법,2024-10-01,"7,297,350,650",11.9%,"7,385,538,550","774,053","783,106","1,101","65,414",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.10
3,4,조커: 폴리 아 되,2024-10-01,"6,366,573,920",10.4%,"6,377,181,920","611,371","611,995","1,385","45,742",미국,미국,워너브러더스 코리아(주),24.10
4,5,와일드 로봇,2024-10-01,"5,391,693,670",8.8%,"5,502,661,670","595,334","606,448","1,062","42,261",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.10

In [44]:
df18.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df18.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,베테랑2,2024-09-13,"62,497,677,496",62.4%,"62,497,677,496","6,489,383","6,489,383","2,691","200,561",한국,한국,(주)씨제이이엔엠,24.09
1,2,에이리언: 로물루스,2024-08-14,"4,400,663,791",4.4%,"20,405,247,130","438,500","1,998,630","1,009","41,535",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.09
2,3,사랑의 하츄핑,2024-08-07,"2,596,577,910",2.6%,"10,276,474,432","297,701","1,147,527",690,"14,411",한국,한국,(주)쇼박스,24.09
3,4,"안녕, 할부지",2024-09-04,"2,281,541,639",2.3%,"2,317,495,639","246,581","250,528","1,021","28,065",한국,한국,(주)바른손이앤에이,24.09
4,5,파일럿,2024-07-31,"2,020,981,840",2.0%,"43,091,622,701","244,276","4,702,215",840,"25,057",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,24.09

In [45]:
df = pd.concat([df18, df17])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,베테랑2,2024-09-13,"62,497,677,496",62.4%,"62,497,677,496","6,489,383","6,489,383","2,691","200,561",한국,한국,(주)씨제이이엔엠,24.09
1,2,에이리언: 로물루스,2024-08-14,"4,400,663,791",4.4%,"20,405,247,130","438,500","1,998,630","1,009","41,535",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.09
2,3,사랑의 하츄핑,2024-08-07,"2,596,577,910",2.6%,"10,276,474,432","297,701","1,147,527",690,"14,411",한국,한국,(주)쇼박스,24.09
3,4,"안녕, 할부지",2024-09-04,"2,281,541,639",2.3%,"2,317,495,639","246,581","250,528","1,021","28,065",한국,한국,(주)바른손이앤에이,24.09
4,5,파일럿,2024-07-31,"2,020,981,840",2.0%,"43,091,622,701","244,276","4,702,215",840,"25,057",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,24.09

In [46]:
df.to_csv("240910.csv", index=False)

In [57]:
df=pd.read_csv("KOBIS_월별박스오피스_241112.csv")

In [53]:
df19 = df.iloc[7:735].reset_index(drop=True)
df19.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,소방관,2024-12-04,"31,098,404,290",25.0%,"31,161,375,290","3,310,323","3,317,296","1,594","119,743",한국,한국,(주)바이포엠스튜디오
1,2,하얼빈,2024-12-24,"26,249,028,320",21.1%,"26,249,028,320","2,755,236","2,755,236","2,125","72,494",한국,한국,(주)씨제이이엔엠
2,3,모아나 2,2024-11-27,"22,727,697,820",18.3%,"31,118,051,070","2,441,529","3,372,815","1,985","95,741",미국,"미국,캐나다",월트디즈니컴퍼니코리아 유한책임회사
3,4,위키드,2024-11-20,"9,685,624,650",7.8%,"20,277,702,850","987,630","2,059,163","1,151","44,301",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
4,5,무파사: 라이온 킹,2024-12-18,"6,543,943,550",5.3%,"6,543,943,550","656,645","656,645","1,243","33,414",미국,미국,월트디즈니컴퍼니코리아 유한책임회사

In [54]:
df19.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
723,697,제1회 부산국제인공지능영화제 섹션5,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
724,697,제1회 부산국제인공지능영화제 섹션6,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN
725,697,백야의 언약 상영회,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
726,697,2024 한양대학교 졸업영화제 섹션1,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
727,697,세기말의 사랑,2024-01-24,0,0.0%,"101,133,958",0,"12,139",1,2,한국,한국,"(주)엔케이컨텐츠,(주)디스테이션"

In [61]:
df20 = df.iloc[740:-1].reset_index(drop=True)
df20.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,위키드,2024-11-20,"10,592,078,200",16.0%,"10,592,078,200","1,071,533","1,071,533","1,803","50,949",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
1,2,모아나 2,2024-11-27,"8,390,353,250",12.7%,"8,390,353,250","931,286","931,286","1,974","30,841",미국,"미국,캐나다",월트디즈니컴퍼니코리아 유한책임회사
2,3,글래디에이터 Ⅱ,2024-11-13,"8,219,618,370",12.4%,"8,221,729,370","841,741","841,964","1,769","57,272",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
3,4,청설,2024-11-06,"7,139,987,740",10.8%,"7,154,611,740","763,788","765,212","1,060","59,671",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
4,5,베놈: 라스트 댄스,2024-10-23,"7,350,822,100",11.1%,"17,198,484,488","752,212","1,757,623","1,326","59,389",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점

In [62]:
df20.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
896,844,바후발리: 더 컨클루전,NaN,0,0.0%,0,0,0,1,1,인도,인도,NaN
897,844,쓰리 오브 어스,NaN,0,0.0%,0,0,0,1,2,인도,인도,NaN
898,844,칸타라,NaN,0,0.0%,0,0,0,1,1,인도,인도,NaN
899,844,라파타 레이디스,NaN,0,0.0%,0,0,0,1,2,인도,인도,NaN
900,844,아이다호,NaN,0,0.0%,"60,348,900",0,"7,305",1,1,미국,미국,NaN

In [63]:
df19["month"]="24.12"
df20["month"]="24.11"

In [64]:
df19.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df19.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,소방관,2024-12-04,"31,098,404,290",25.0%,"31,161,375,290","3,310,323","3,317,296","1,594","119,743",한국,한국,(주)바이포엠스튜디오,24.12
1,2,하얼빈,2024-12-24,"26,249,028,320",21.1%,"26,249,028,320","2,755,236","2,755,236","2,125","72,494",한국,한국,(주)씨제이이엔엠,24.12
2,3,모아나 2,2024-11-27,"22,727,697,820",18.3%,"31,118,051,070","2,441,529","3,372,815","1,985","95,741",미국,"미국,캐나다",월트디즈니컴퍼니코리아 유한책임회사,24.12
3,4,위키드,2024-11-20,"9,685,624,650",7.8%,"20,277,702,850","987,630","2,059,163","1,151","44,301",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.12
4,5,무파사: 라이온 킹,2024-12-18,"6,543,943,550",5.3%,"6,543,943,550","656,645","656,645","1,243","33,414",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,24.12

In [65]:
df20.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df20.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,위키드,2024-11-20,"10,592,078,200",16.0%,"10,592,078,200","1,071,533","1,071,533","1,803","50,949",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.11
1,2,모아나 2,2024-11-27,"8,390,353,250",12.7%,"8,390,353,250","931,286","931,286","1,974","30,841",미국,"미국,캐나다",월트디즈니컴퍼니코리아 유한책임회사,24.11
2,3,글래디에이터 Ⅱ,2024-11-13,"8,219,618,370",12.4%,"8,221,729,370","841,741","841,964","1,769","57,272",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,24.11
3,4,청설,2024-11-06,"7,139,987,740",10.8%,"7,154,611,740","763,788","765,212","1,060","59,671",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.11
4,5,베놈: 라스트 댄스,2024-10-23,"7,350,822,100",11.1%,"17,198,484,488","752,212","1,757,623","1,326","59,389",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,24.11

In [66]:
df = pd.concat([df20, df19])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,위키드,2024-11-20,"10,592,078,200",16.0%,"10,592,078,200","1,071,533","1,071,533","1,803","50,949",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),24.11
1,2,모아나 2,2024-11-27,"8,390,353,250",12.7%,"8,390,353,250","931,286","931,286","1,974","30,841",미국,"미국,캐나다",월트디즈니컴퍼니코리아 유한책임회사,24.11
2,3,글래디에이터 Ⅱ,2024-11-13,"8,219,618,370",12.4%,"8,221,729,370","841,741","841,964","1,769","57,272",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,24.11
3,4,청설,2024-11-06,"7,139,987,740",10.8%,"7,154,611,740","763,788","765,212","1,060","59,671",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,24.11
4,5,베놈: 라스트 댄스,2024-10-23,"7,350,822,100",11.1%,"17,198,484,488","752,212","1,757,623","1,326","59,389",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,24.11

In [67]:
df.to_csv("241112.csv", index=False)

In [68]:
df=pd.read_csv("KOBIS_월별박스오피스_250102.csv")

In [70]:
df21 = df.iloc[7:450].reset_index(drop=True)
df21.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,캡틴 아메리카: 브레이브 뉴 월드,2025-02-12,"14,554,372,506",27.4%,"14,554,372,506","1,464,276","1,464,276","1,901","103,015",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,히트맨2,2025-01-22,"8,360,342,240",15.7%,"23,937,166,980","887,949","2,542,377","1,495","66,343",한국,한국,(주)바이포엠스튜디오
2,3,말할 수 없는 비밀,2025-01-27,"5,534,030,180",10.4%,"7,752,532,100","577,640","812,933",986,"49,827",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
3,4,검은 수녀들,2025-01-24,"3,838,046,760",7.2%,"16,109,391,280","398,774","1,666,571","1,192","37,147",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
4,5,미키 17,2025-02-28,"2,547,448,920",4.8%,"2,547,448,920","254,393","254,393","2,151","8,794",미국,미국,워너브러더스 코리아(주)

In [71]:
df21.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
438,436,반칙왕,2000-02-04,0,0.0%,0,0,0,1,2,한국,한국,(주)시네마서비스
439,436,서울의 지붕 밑,NaN,0,0.0%,0,0,0,1,2,한국,한국,NaN
440,436,삼등과장,NaN,0,0.0%,0,0,0,1,2,한국,한국,NaN
441,436,돈,1950-03-09,0,0.0%,0,0,0,1,2,한국,한국,NaN
442,436,뭉호,NaN,0,0.0%,0,0,0,1,2,몽고,몽고,NaN

In [74]:
df22 = df.iloc[455:-1].reset_index(drop=True)
df22.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,하얼빈,2024-12-24,"19,891,094,780",23.3%,"46,140,123,100","2,068,563","4,823,799","1,425","116,074",한국,한국,(주)씨제이이엔엠
1,2,히트맨2,2025-01-22,"15,576,824,740",18.3%,"15,576,824,740","1,654,428","1,654,428","1,588","51,754",한국,한국,(주)바이포엠스튜디오
2,3,검은 수녀들,2025-01-24,"12,271,344,520",14.4%,"12,271,344,520","1,267,797","1,267,797","1,662","47,087",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
3,4,소방관,2024-12-04,"5,084,748,380",6.0%,"36,246,123,670","533,707","3,851,003",884,"42,465",한국,한국,(주)바이포엠스튜디오
4,5,뽀로로 극장판 바닷속 대모험,2025-01-01,"2,926,095,680",3.4%,"3,242,433,070","342,639","376,594",791,"21,977",한국,한국,씨제이 씨지브이(CJ CGV)(주)

In [75]:
df22.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
438,371,웹캠:성욕과 물터지는 섹시한 가정부,2025-01-31,"6,000",0.0%,"6,000",1,1,1,1,일본,일본,(주)영진크리에이티브
439,371,골 때리고 떡 때리는 그녀들: 후반,2025-01-24,"1,000",0.0%,"1,000",1,1,1,1,한국,한국,유한회사 영화사 반딧불
440,441,귀여워,2004-11-26,0,0.0%,"327,309,000",0,"51,284",1,2,한국,한국,(주)튜브엔터테인먼트
441,441,여자는 남자의 미래다,2004-05-05,0,0.0%,"778,809,500",0,"116,662",1,2,한국,한국,씨제이엔터테인먼트
442,441,하류인생,2004-05-21,0,0.0%,"1,471,268,000",0,"224,856",1,2,한국,한국,(주)시네마서비스

In [76]:
df21["month"]="25.02"
df22["month"]="25.01"

In [77]:
df21.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df21.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,캡틴 아메리카: 브레이브 뉴 월드,2025-02-12,"14,554,372,506",27.4%,"14,554,372,506","1,464,276","1,464,276","1,901","103,015",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.02
1,2,히트맨2,2025-01-22,"8,360,342,240",15.7%,"23,937,166,980","887,949","2,542,377","1,495","66,343",한국,한국,(주)바이포엠스튜디오,25.02
2,3,말할 수 없는 비밀,2025-01-27,"5,534,030,180",10.4%,"7,752,532,100","577,640","812,933",986,"49,827",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,25.02
3,4,검은 수녀들,2025-01-24,"3,838,046,760",7.2%,"16,109,391,280","398,774","1,666,571","1,192","37,147",한국,한국,(주)넥스트엔터테인먼트월드(NEW),25.02
4,5,미키 17,2025-02-28,"2,547,448,920",4.8%,"2,547,448,920","254,393","254,393","2,151","8,794",미국,미국,워너브러더스 코리아(주),25.02

In [78]:
df22.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df22.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,하얼빈,2024-12-24,"19,891,094,780",23.3%,"46,140,123,100","2,068,563","4,823,799","1,425","116,074",한국,한국,(주)씨제이이엔엠,25.01
1,2,히트맨2,2025-01-22,"15,576,824,740",18.3%,"15,576,824,740","1,654,428","1,654,428","1,588","51,754",한국,한국,(주)바이포엠스튜디오,25.01
2,3,검은 수녀들,2025-01-24,"12,271,344,520",14.4%,"12,271,344,520","1,267,797","1,267,797","1,662","47,087",한국,한국,(주)넥스트엔터테인먼트월드(NEW),25.01
3,4,소방관,2024-12-04,"5,084,748,380",6.0%,"36,246,123,670","533,707","3,851,003",884,"42,465",한국,한국,(주)바이포엠스튜디오,25.01
4,5,뽀로로 극장판 바닷속 대모험,2025-01-01,"2,926,095,680",3.4%,"3,242,433,070","342,639","376,594",791,"21,977",한국,한국,씨제이 씨지브이(CJ CGV)(주),25.01

In [79]:
df = pd.concat([df22, df21])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,하얼빈,2024-12-24,"19,891,094,780",23.3%,"46,140,123,100","2,068,563","4,823,799","1,425","116,074",한국,한국,(주)씨제이이엔엠,25.01
1,2,히트맨2,2025-01-22,"15,576,824,740",18.3%,"15,576,824,740","1,654,428","1,654,428","1,588","51,754",한국,한국,(주)바이포엠스튜디오,25.01
2,3,검은 수녀들,2025-01-24,"12,271,344,520",14.4%,"12,271,344,520","1,267,797","1,267,797","1,662","47,087",한국,한국,(주)넥스트엔터테인먼트월드(NEW),25.01
3,4,소방관,2024-12-04,"5,084,748,380",6.0%,"36,246,123,670","533,707","3,851,003",884,"42,465",한국,한국,(주)바이포엠스튜디오,25.01
4,5,뽀로로 극장판 바닷속 대모험,2025-01-01,"2,926,095,680",3.4%,"3,242,433,070","342,639","376,594",791,"21,977",한국,한국,씨제이 씨지브이(CJ CGV)(주),25.01

In [80]:
df.to_csv("250102.csv", index=False)

In [94]:
df=pd.read_csv("KOBIS_월별박스오피스_250304.csv")

In [95]:
df23 = df.iloc[7:592].reset_index(drop=True)
df23.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,야당,2025-04-16,"17,335,200,590",33.9%,"17,338,269,590","1,841,518","1,841,797","1,850","100,486",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
1,2,승부,2025-03-26,"12,678,579,880",24.8%,"19,805,992,760","1,350,527","2,119,764","1,548","105,224",한국,한국,(주)바이포엠스튜디오
2,3,A MINECRAFT MOVIE 마인크래프트 무비,2025-04-26,"4,019,940,940",7.9%,"4,019,940,940","423,665","423,665","1,450","19,653",미국,미국,워너브러더스 코리아(주)
3,4,로비,2025-04-02,"2,413,028,740",4.7%,"2,456,403,340","255,534","260,151","1,013","32,929",한국,한국,(주)쇼박스
4,5,극장판 진격의 거인 완결편 더 라스트 어택,2025-03-13,"2,635,164,810",5.2%,"8,096,849,070","250,600","801,506",298,"16,007",일본,일본,(주)애니플러스

In [96]:
df23.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
580,575,리골레토,2020-04-05,0,0.0%,0,0,0,1,1,독일,독일,(주)케빈앤컴퍼니
581,575,한국이 싫어서,2024-08-28,0,0.0%,0,0,0,1,1,한국,한국,(주)디스테이션
582,575,딸에 대하여,2024-09-04,0,0.0%,"198,493,780",0,"21,858",1,1,한국,한국,"찬란,스튜디오 에이드"
583,575,제3회 강릉국제아트페스티벌 섹션,NaN,0,0.0%,0,0,0,1,9,한국,한국,NaN
584,575,"광해, 왕이 된 남자",2012-09-13,0,0.0%,0,0,0,1,1,한국,한국,(주)씨제이이엔엠

In [97]:
df24 = df.iloc[597:-1].reset_index(drop=True)
df24.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,미키 17,2025-02-28,"26,703,536,310",43.1%,"29,250,985,230","2,712,431","2,966,824","2,153","141,207",미국,미국,워너브러더스 코리아(주)
1,2,승부,2025-03-26,"7,127,412,880",11.5%,"7,127,412,880","769,237","769,237","1,773","42,711",한국,한국,(주)바이포엠스튜디오
2,3,극장판 진격의 거인 완결편 더 라스트 어택,2025-03-13,"5,461,684,260",8.8%,"5,461,684,260","550,906","550,906",424,"18,954",일본,일본,(주)애니플러스
3,4,퇴마록,2025-02-21,"2,736,497,180",4.4%,"4,663,601,900","288,325","491,363",935,"28,656",한국,한국,(주)쇼박스
4,5,콘클라베,2025-03-05,"2,186,519,100",3.5%,"2,221,690,500","230,536","234,152",630,"20,735",미국,미국,(주)디스테이션

In [98]:
df24.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
431,432,제3회 강릉국제아트페스티벌 섹션,NaN,0,0.0%,0,0,0,1,9,한국,한국,NaN
432,432,구룡성채: 무법지대,2024-10-16,0,0.0%,"99,318,950",0,"11,562",1,1,홍콩,홍콩,(주)콘텐츠판다
433,432,우리 학교,2007-03-29,0,0.0%,"213,869,000",0,"34,852",1,2,한국,한국,"(주)영화사 진진,아트플러스시네마네트워크"
434,432,다세포소녀,2006-08-10,0,0.0%,"2,858,283,600",0,"476,011",1,2,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
435,432,우리들의 일그러진 영웅,1992-08-15,0,0.0%,0,0,0,1,2,한국,한국,NaN

In [99]:
df23["month"]="25.04"
df24["month"]="25.03"

In [100]:
df23.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df23.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,야당,2025-04-16,"17,335,200,590",33.9%,"17,338,269,590","1,841,518","1,841,797","1,850","100,486",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,25.04
1,2,승부,2025-03-26,"12,678,579,880",24.8%,"19,805,992,760","1,350,527","2,119,764","1,548","105,224",한국,한국,(주)바이포엠스튜디오,25.04
2,3,A MINECRAFT MOVIE 마인크래프트 무비,2025-04-26,"4,019,940,940",7.9%,"4,019,940,940","423,665","423,665","1,450","19,653",미국,미국,워너브러더스 코리아(주),25.04
3,4,로비,2025-04-02,"2,413,028,740",4.7%,"2,456,403,340","255,534","260,151","1,013","32,929",한국,한국,(주)쇼박스,25.04
4,5,극장판 진격의 거인 완결편 더 라스트 어택,2025-03-13,"2,635,164,810",5.2%,"8,096,849,070","250,600","801,506",298,"16,007",일본,일본,(주)애니플러스,25.04

In [101]:
df24.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df24.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,미키 17,2025-02-28,"26,703,536,310",43.1%,"29,250,985,230","2,712,431","2,966,824","2,153","141,207",미국,미국,워너브러더스 코리아(주),25.03
1,2,승부,2025-03-26,"7,127,412,880",11.5%,"7,127,412,880","769,237","769,237","1,773","42,711",한국,한국,(주)바이포엠스튜디오,25.03
2,3,극장판 진격의 거인 완결편 더 라스트 어택,2025-03-13,"5,461,684,260",8.8%,"5,461,684,260","550,906","550,906",424,"18,954",일본,일본,(주)애니플러스,25.03
3,4,퇴마록,2025-02-21,"2,736,497,180",4.4%,"4,663,601,900","288,325","491,363",935,"28,656",한국,한국,(주)쇼박스,25.03
4,5,콘클라베,2025-03-05,"2,186,519,100",3.5%,"2,221,690,500","230,536","234,152",630,"20,735",미국,미국,(주)디스테이션,25.03

In [102]:
df = pd.concat([df24, df23])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,미키 17,2025-02-28,"26,703,536,310",43.1%,"29,250,985,230","2,712,431","2,966,824","2,153","141,207",미국,미국,워너브러더스 코리아(주),25.03
1,2,승부,2025-03-26,"7,127,412,880",11.5%,"7,127,412,880","769,237","769,237","1,773","42,711",한국,한국,(주)바이포엠스튜디오,25.03
2,3,극장판 진격의 거인 완결편 더 라스트 어택,2025-03-13,"5,461,684,260",8.8%,"5,461,684,260","550,906","550,906",424,"18,954",일본,일본,(주)애니플러스,25.03
3,4,퇴마록,2025-02-21,"2,736,497,180",4.4%,"4,663,601,900","288,325","491,363",935,"28,656",한국,한국,(주)쇼박스,25.03
4,5,콘클라베,2025-03-05,"2,186,519,100",3.5%,"2,221,690,500","230,536","234,152",630,"20,735",미국,미국,(주)디스테이션,25.03

In [104]:
df.tail()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
580,575,리골레토,2020-04-05,0,0.0%,0,0,0,1,1,독일,독일,(주)케빈앤컴퍼니,25.04
581,575,한국이 싫어서,2024-08-28,0,0.0%,0,0,0,1,1,한국,한국,(주)디스테이션,25.04
582,575,딸에 대하여,2024-09-04,0,0.0%,"198,493,780",0,"21,858",1,1,한국,한국,"찬란,스튜디오 에이드",25.04
583,575,제3회 강릉국제아트페스티벌 섹션,NaN,0,0.0%,0,0,0,1,9,한국,한국,NaN,25.04
584,575,"광해, 왕이 된 남자",2012-09-13,0,0.0%,0,0,0,1,1,한국,한국,(주)씨제이이엔엠,25.04

In [105]:
df.to_csv("250304.csv", index=False)

In [106]:
df=pd.read_csv("KOBIS_월별박스오피스_250506.csv")

In [111]:
df25 = df.iloc[7:678].reset_index(drop=True)
df25.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,하이파이브,2025-05-30,"14,925,913,580",20.2%,"17,159,791,010","1,612,363","1,849,352","1,343","89,153",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
1,2,드래곤 길들이기,2025-06-06,"15,566,398,960",21.1%,"15,611,823,960","1,544,510","1,547,247","1,650","78,571",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
2,3,미션 임파서블: 파이널 레코닝,2025-05-17,"9,883,322,550",13.4%,"32,948,734,860","1,025,274","3,360,001","1,365","53,463",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
3,4,신명,2025-06-02,"7,042,863,160",9.5%,"7,179,717,660","739,317","752,149",785,"36,676",한국,한국,"(주)열공영화제작소,(주)스마일이엔티,주식회사 블루필름웍스"
4,5,F1 더 무비,2025-06-25,"5,765,519,060",7.8%,"5,765,519,060","534,899","534,899","1,665","30,339",미국,미국,워너브러더스 코리아(주)

In [112]:
df25.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
666,646,수학여행,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
667,646,사람의 아들,1981-01-01,0,0.0%,0,0,0,1,1,한국,한국,NaN
668,646,장미빛 인생,1994-08-06,0,0.0%,0,0,0,1,2,한국,한국,NaN
669,646,조용한 가족,1998-04-25,0,0.0%,0,0,0,1,2,한국,한국,NaN
670,646,미도리,NaN,0,0.0%,0,0,0,1,1,일본,일본,NaN

In [114]:
df26 = df.iloc[683:-1].reset_index(drop=True)
df26.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,미션 임파서블: 파이널 레코닝,2025-05-17,"23,065,412,310",28.0%,"23,065,412,310","2,334,727","2,334,727","2,385","94,508",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트
1,2,야당,2025-04-16,"14,530,617,340",17.6%,"31,868,886,930","1,522,463","3,364,260","1,441","81,704",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
2,3,A MINECRAFT MOVIE 마인크래프트 무비,2025-04-26,"8,637,220,530",10.5%,"12,657,161,470","925,266","1,348,931","1,415","35,778",미국,미국,워너브러더스 코리아(주)
3,4,썬더볼츠＊,2025-04-30,"8,343,968,950",10.1%,"9,259,331,560","818,769","920,192","1,236","52,501",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
4,5,거룩한 밤: 데몬 헌터스,2025-04-30,"6,230,473,900",7.6%,"7,203,375,200","655,989","777,308","1,097","36,071",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트

In [115]:
df26.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
618,578,붉은 아이들의 길,NaN,0,0.0%,0,0,0,1,2,기타,"기타,프랑스,벨기에",NaN
619,578,예언,NaN,0,0.0%,0,0,0,1,2,기타,"기타,벨기에,네덜란드",NaN
620,578,어부와 말하는 물고기,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN
621,578,여자들,NaN,0,0.0%,0,0,0,1,2,기타,기타,NaN
622,578,굿바이 줄리아,NaN,0,0.0%,"480,000",0,160,1,3,기타,기타,NaN

In [117]:
df25["month"]="25.06"
df26["month"]="25.05"

In [119]:
df25.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df25.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,하이파이브,2025-05-30,"14,925,913,580",20.2%,"17,159,791,010","1,612,363","1,849,352","1,343","89,153",한국,한국,(주)넥스트엔터테인먼트월드(NEW),25.06
1,2,드래곤 길들이기,2025-06-06,"15,566,398,960",21.1%,"15,611,823,960","1,544,510","1,547,247","1,650","78,571",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),25.06
2,3,미션 임파서블: 파이널 레코닝,2025-05-17,"9,883,322,550",13.4%,"32,948,734,860","1,025,274","3,360,001","1,365","53,463",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,25.06
3,4,신명,2025-06-02,"7,042,863,160",9.5%,"7,179,717,660","739,317","752,149",785,"36,676",한국,한국,"(주)열공영화제작소,(주)스마일이엔티,주식회사 블루필름웍스",25.06
4,5,F1 더 무비,2025-06-25,"5,765,519,060",7.8%,"5,765,519,060","534,899","534,899","1,665","30,339",미국,미국,워너브러더스 코리아(주),25.06

In [120]:
df26.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df26.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,미션 임파서블: 파이널 레코닝,2025-05-17,"23,065,412,310",28.0%,"23,065,412,310","2,334,727","2,334,727","2,385","94,508",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,25.05
1,2,야당,2025-04-16,"14,530,617,340",17.6%,"31,868,886,930","1,522,463","3,364,260","1,441","81,704",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,25.05
2,3,A MINECRAFT MOVIE 마인크래프트 무비,2025-04-26,"8,637,220,530",10.5%,"12,657,161,470","925,266","1,348,931","1,415","35,778",미국,미국,워너브러더스 코리아(주),25.05
3,4,썬더볼츠＊,2025-04-30,"8,343,968,950",10.1%,"9,259,331,560","818,769","920,192","1,236","52,501",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.05
4,5,거룩한 밤: 데몬 헌터스,2025-04-30,"6,230,473,900",7.6%,"7,203,375,200","655,989","777,308","1,097","36,071",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,25.05

In [121]:
df = pd.concat([df26, df25])

In [122]:
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,미션 임파서블: 파이널 레코닝,2025-05-17,"23,065,412,310",28.0%,"23,065,412,310","2,334,727","2,334,727","2,385","94,508",미국,미국,롯데컬처웍스(주)롯데엔터테인먼트,25.05
1,2,야당,2025-04-16,"14,530,617,340",17.6%,"31,868,886,930","1,522,463","3,364,260","1,441","81,704",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,25.05
2,3,A MINECRAFT MOVIE 마인크래프트 무비,2025-04-26,"8,637,220,530",10.5%,"12,657,161,470","925,266","1,348,931","1,415","35,778",미국,미국,워너브러더스 코리아(주),25.05
3,4,썬더볼츠＊,2025-04-30,"8,343,968,950",10.1%,"9,259,331,560","818,769","920,192","1,236","52,501",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.05
4,5,거룩한 밤: 데몬 헌터스,2025-04-30,"6,230,473,900",7.6%,"7,203,375,200","655,989","777,308","1,097","36,071",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,25.05

In [123]:
df.to_csv("250506.csv", index=False)

In [124]:
df=pd.read_csv("KOBIS_월별박스오피스_250708.csv")

In [129]:
df27 = df.iloc[7:755].reset_index(drop=True)
df27.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,좀비딸,2025-07-30,"44,745,898,810",33.0%,"50,677,473,110","4,644,095","5,347,076","1,598","151,123",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
1,2,극장판 귀멸의 칼날: 무한성편,2025-08-22,"34,047,039,980",25.1%,"34,047,039,980","3,153,718","3,153,718","2,298","74,827",일본,일본,(주)씨제이이엔엠
2,3,F1 더 무비,2025-06-25,"22,241,743,450",16.4%,"51,134,093,100","2,048,088","4,760,384",981,"66,530",미국,미국,워너브러더스 코리아(주)
3,4,킹 오브 킹스,2025-07-16,"3,969,127,900",2.9%,"12,226,901,076","419,093","1,296,035",814,"18,221",한국,한국,(주)디스테이션
4,5,악마가 이사왔다,2025-08-13,"3,963,230,310",2.9%,"3,963,230,310","417,227","417,227",974,"30,705",한국,한국,(주)씨제이이엔엠

In [130]:
df27.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
743,734,2025 로컬-시내(Ciné) : 지역영화 교류전 - 섹션2 WOMEN IN FOCUS,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
744,734,2025 로컬-시내(Ciné) : 지역영화 교류전 - 섹션3 DREAMERS,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
745,734,2025 로컬-시내(Ciné) : 지역영화 교류전 - 섹션1 YOUTH,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
746,734,2025 로컬-시내(Ciné) : 지역영화 교류전 - 섹션4 REALITY,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
747,734,육체의 약속,1975-07-26,0,0.0%,0,0,0,1,2,한국,한국,NaN

In [132]:
df28 = df.iloc[760:-1].reset_index(drop=True)
df28.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,쥬라기 월드: 새로운 시작,2025-07-02,"20,937,554,270",18.2%,"20,946,092,270","2,197,632","2,198,202","1,645","86,451",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
1,2,F1 더 무비,2025-06-25,"23,126,830,590",20.1%,"28,892,349,650","2,177,397","2,712,296","1,382","69,260",미국,미국,워너브러더스 코리아(주)
2,3,노이즈,2025-06-25,"14,214,389,760",12.4%,"16,454,268,630","1,445,177","1,678,135","1,001","59,840",한국,한국,(주)바이포엠스튜디오
3,4,킹 오브 킹스,2025-07-16,"8,237,623,176",7.2%,"8,257,773,176","875,009","876,942","1,191","33,337",한국,한국,(주)디스테이션
4,5,전지적 독자 시점,2025-07-23,"8,356,959,660",7.3%,"8,356,959,660","857,450","857,450","1,581","37,963",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트

In [134]:
df28.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
655,647,막차로 온 손님들,NaN,0,0.0%,"908,000",0,454,1,2,한국,한국,NaN
656,647,카인의 후예,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
657,647,수학여행,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
658,647,장마,NaN,0,0.0%,"9,697,000",0,"4,843",1,2,한국,한국,(주)프리즘웍스
659,647,그대와 영원히,1958-01-15,0,0.0%,"5,772,500",0,"2,721",1,1,한국,한국,NaN

In [135]:
df27["month"]="25.08"
df28["month"]="25.07"

In [136]:
df27.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df27.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,좀비딸,2025-07-30,"44,745,898,810",33.0%,"50,677,473,110","4,644,095","5,347,076","1,598","151,123",한국,한국,(주)넥스트엔터테인먼트월드(NEW),25.08
1,2,극장판 귀멸의 칼날: 무한성편,2025-08-22,"34,047,039,980",25.1%,"34,047,039,980","3,153,718","3,153,718","2,298","74,827",일본,일본,(주)씨제이이엔엠,25.08
2,3,F1 더 무비,2025-06-25,"22,241,743,450",16.4%,"51,134,093,100","2,048,088","4,760,384",981,"66,530",미국,미국,워너브러더스 코리아(주),25.08
3,4,킹 오브 킹스,2025-07-16,"3,969,127,900",2.9%,"12,226,901,076","419,093","1,296,035",814,"18,221",한국,한국,(주)디스테이션,25.08
4,5,악마가 이사왔다,2025-08-13,"3,963,230,310",2.9%,"3,963,230,310","417,227","417,227",974,"30,705",한국,한국,(주)씨제이이엔엠,25.08

In [137]:
df28.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df28.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,쥬라기 월드: 새로운 시작,2025-07-02,"20,937,554,270",18.2%,"20,946,092,270","2,197,632","2,198,202","1,645","86,451",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),25.07
1,2,F1 더 무비,2025-06-25,"23,126,830,590",20.1%,"28,892,349,650","2,177,397","2,712,296","1,382","69,260",미국,미국,워너브러더스 코리아(주),25.07
2,3,노이즈,2025-06-25,"14,214,389,760",12.4%,"16,454,268,630","1,445,177","1,678,135","1,001","59,840",한국,한국,(주)바이포엠스튜디오,25.07
3,4,킹 오브 킹스,2025-07-16,"8,237,623,176",7.2%,"8,257,773,176","875,009","876,942","1,191","33,337",한국,한국,(주)디스테이션,25.07
4,5,전지적 독자 시점,2025-07-23,"8,356,959,660",7.3%,"8,356,959,660","857,450","857,450","1,581","37,963",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,25.07

In [139]:
df = pd.concat([df28, df27])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,쥬라기 월드: 새로운 시작,2025-07-02,"20,937,554,270",18.2%,"20,946,092,270","2,197,632","2,198,202","1,645","86,451",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),25.07
1,2,F1 더 무비,2025-06-25,"23,126,830,590",20.1%,"28,892,349,650","2,177,397","2,712,296","1,382","69,260",미국,미국,워너브러더스 코리아(주),25.07
2,3,노이즈,2025-06-25,"14,214,389,760",12.4%,"16,454,268,630","1,445,177","1,678,135","1,001","59,840",한국,한국,(주)바이포엠스튜디오,25.07
3,4,킹 오브 킹스,2025-07-16,"8,237,623,176",7.2%,"8,257,773,176","875,009","876,942","1,191","33,337",한국,한국,(주)디스테이션,25.07
4,5,전지적 독자 시점,2025-07-23,"8,356,959,660",7.3%,"8,356,959,660","857,450","857,450","1,581","37,963",한국,한국,롯데컬처웍스(주)롯데엔터테인먼트,25.07

In [140]:
df.to_csv("250708.csv", index=False)

In [141]:
df=pd.read_csv("KOBIS_월별박스오피스_250910.csv")

In [145]:
df29 = df.iloc[7:883].reset_index(drop=True)
df29.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,보스,2025-10-03,"23,122,825,490",23.5%,"23,167,398,990","2,407,846","2,412,606","1,296","94,008",한국,한국,"(주)하이브미디어코프,(주)마인드마크"
1,2,극장판 체인소 맨: 레제편,2025-09-24,"22,189,517,940",22.6%,"28,317,601,570","2,095,675","2,675,054",998,"89,330",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
2,3,어쩔수가없다,2025-09-24,"16,367,343,620",16.7%,"28,403,760,090","1,670,838","2,905,075","1,353","74,795",한국,한국,(주)씨제이이엔엠
3,4,극장판 귀멸의 칼날: 무한성편,2025-08-22,"5,358,829,390",5.5%,"59,898,105,010","523,088","5,549,749",635,"22,420",일본,일본,(주)씨제이이엔엠
4,5,원 배틀 애프터 어나더,2025-10-01,"5,393,791,240",5.5%,"5,427,443,740","507,628","509,912",657,"25,461",미국,미국,워너브러더스 코리아(주)

In [146]:
df29.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
871,848,빌리 엘리어트,2001-02-16,0,0.0%,0,0,0,1,2,영국,"영국,프랑스","(주)팝엔터테인먼트,유아이피-씨아이씨영화및비디오배급(유)"
872,848,아무도 모른다,2005-04-01,0,0.0%,0,0,0,1,1,일본,일본,"(주)디스테이션,(주)동숭아트센터"
873,848,미망인,1955-12-10,0,0.0%,0,0,0,1,1,한국,한국,NaN
874,848,돌아오지 않는 해병,NaN,0,0.0%,0,0,0,1,2,한국,한국,NaN
875,848,16회 부산평화영화제 폐막식,NaN,0,0.0%,0,0,0,1,1,기타,기타,NaN

In [148]:
df30 = df.iloc[888:-1].reset_index(drop=True)
df30.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,극장판 귀멸의 칼날: 무한성편,2025-08-22,"20,492,235,640",26.3%,"54,539,275,620","1,872,943","5,026,661","1,761","97,946",일본,일본,(주)씨제이이엔엠
1,2,어쩔수가없다,2025-09-24,"12,035,520,470",15.5%,"12,036,416,470","1,234,173","1,234,237","2,114","47,093",한국,한국,(주)씨제이이엔엠
2,3,얼굴,2025-09-11,"9,599,367,010",12.3%,"9,599,367,010","932,553","932,553","1,114","53,480",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트
3,4,극장판 체인소 맨: 레제편,2025-09-24,"6,128,083,630",7.9%,"6,128,083,630","579,379","579,379","1,064","21,662",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
4,5,컨저링: 마지막 의식,2025-09-03,"4,419,577,290",5.7%,"4,423,114,290","419,157","419,502",917,"27,094",미국,미국,워너브러더스 코리아(주)

In [149]:
df30.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
825,812,지역의 기억 - 단편,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
826,812,깁,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
827,812,김종관 단편선 1,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
828,812,김종관 단편선 2,NaN,0,0.0%,0,0,0,1,1,한국,한국,NaN
829,812,최악의 하루,2016-08-25,0,0.0%,"648,824,890",0,"81,919",1,1,한국,한국,CGV아트하우스

In [150]:
df29["month"]="25.10"
df30["month"]="25.09"

In [151]:
df29.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df29.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,보스,2025-10-03,"23,122,825,490",23.5%,"23,167,398,990","2,407,846","2,412,606","1,296","94,008",한국,한국,"(주)하이브미디어코프,(주)마인드마크",25.10
1,2,극장판 체인소 맨: 레제편,2025-09-24,"22,189,517,940",22.6%,"28,317,601,570","2,095,675","2,675,054",998,"89,330",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.10
2,3,어쩔수가없다,2025-09-24,"16,367,343,620",16.7%,"28,403,760,090","1,670,838","2,905,075","1,353","74,795",한국,한국,(주)씨제이이엔엠,25.10
3,4,극장판 귀멸의 칼날: 무한성편,2025-08-22,"5,358,829,390",5.5%,"59,898,105,010","523,088","5,549,749",635,"22,420",일본,일본,(주)씨제이이엔엠,25.10
4,5,원 배틀 애프터 어나더,2025-10-01,"5,393,791,240",5.5%,"5,427,443,740","507,628","509,912",657,"25,461",미국,미국,워너브러더스 코리아(주),25.10

In [152]:
df30.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df30.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,극장판 귀멸의 칼날: 무한성편,2025-08-22,"20,492,235,640",26.3%,"54,539,275,620","1,872,943","5,026,661","1,761","97,946",일본,일본,(주)씨제이이엔엠,25.09
1,2,어쩔수가없다,2025-09-24,"12,035,520,470",15.5%,"12,036,416,470","1,234,173","1,234,237","2,114","47,093",한국,한국,(주)씨제이이엔엠,25.09
2,3,얼굴,2025-09-11,"9,599,367,010",12.3%,"9,599,367,010","932,553","932,553","1,114","53,480",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,25.09
3,4,극장판 체인소 맨: 레제편,2025-09-24,"6,128,083,630",7.9%,"6,128,083,630","579,379","579,379","1,064","21,662",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.09
4,5,컨저링: 마지막 의식,2025-09-03,"4,419,577,290",5.7%,"4,423,114,290","419,157","419,502",917,"27,094",미국,미국,워너브러더스 코리아(주),25.09

In [153]:
df = pd.concat([df30, df29])

In [155]:
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,극장판 귀멸의 칼날: 무한성편,2025-08-22,"20,492,235,640",26.3%,"54,539,275,620","1,872,943","5,026,661","1,761","97,946",일본,일본,(주)씨제이이엔엠,25.09
1,2,어쩔수가없다,2025-09-24,"12,035,520,470",15.5%,"12,036,416,470","1,234,173","1,234,237","2,114","47,093",한국,한국,(주)씨제이이엔엠,25.09
2,3,얼굴,2025-09-11,"9,599,367,010",12.3%,"9,599,367,010","932,553","932,553","1,114","53,480",한국,한국,메가박스중앙(주) 플러스엠 엔터테인먼트,25.09
3,4,극장판 체인소 맨: 레제편,2025-09-24,"6,128,083,630",7.9%,"6,128,083,630","579,379","579,379","1,064","21,662",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.09
4,5,컨저링: 마지막 의식,2025-09-03,"4,419,577,290",5.7%,"4,423,114,290","419,157","419,502",917,"27,094",미국,미국,워너브러더스 코리아(주),25.09

In [154]:
df.to_csv("250910.csv", index=False)

In [156]:
df=pd.read_csv("KOBIS_월별박스오피스_251112.csv")

In [161]:
df31 = df.iloc[7:854].reset_index(drop=True)
df31.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,주토피아 2,2025-11-26,"53,971,262,890",38.5%,"74,124,615,600","5,598,839","7,705,705","2,282","180,184",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,아바타: 불과 재,2025-12-17,"52,409,899,290",37.4%,"52,409,899,290","4,569,538","4,569,538","2,582","102,298",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,윗집 사람들,2025-12-03,"5,186,086,360",3.7%,"5,284,239,800","537,349","546,584",768,"32,522",한국,한국,(주)바이포엠스튜디오
3,4,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",2025-12-24,"4,681,536,750",3.3%,"4,681,536,750","489,021","489,021",868,"15,093",한국,한국,(주)바이포엠스튜디오
4,5,극장판 주술회전: 시부야사변 X 사멸회유,2025-12-03,"3,628,196,350",2.6%,"3,648,294,490","357,977","359,636",756,"22,831",일본,일본,메가박스중앙(주)

In [162]:
df31.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
842,843,네 멋대로 해라,2026-01-14,"-133,000",0.0%,"9,842,500",-13,"3,272",1,1,프랑스,프랑스,주식회사 오디언스
843,843,누룩,2026-04-15,"-130,000",0.0%,"80,000",-13,8,1,1,한국,한국,(주)로드쇼플러스
844,845,리버 리턴즈,NaN,"-190,000",0.0%,"-190,000",-19,-19,1,2,일본,일본,NaN
845,846,마젤란,NaN,"-260,000",0.0%,"-590,000",-26,-59,1,1,포르투갈,"포르투갈,스페인,프랑스,필리핀,대만",NaN
846,847,사무라이 타임슬리퍼,NaN,"-270,000",0.0%,"-270,000",-27,-27,1,2,일본,일본,NaN

In [164]:
df32 = df.iloc[859:-1].reset_index(drop=True)
df32.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,주토피아 2,2025-11-26,"20,153,352,710",27.9%,"20,153,352,710","2,106,866","2,106,866","2,383","45,432",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
1,2,나우 유 씨 미 3,2025-11-12,"11,862,578,410",16.4%,"11,862,578,410","1,252,092","1,252,092","1,352","65,344",미국,미국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)바이포엠스튜디오"
2,3,위키드: 포 굿,2025-11-19,"8,055,284,900",11.1%,"8,055,284,900","781,928","781,928","1,700","48,403",미국,미국,유니버설픽쳐스인터내셔널 코리아(유)
3,4,극장판 체인소 맨: 레제편,2025-09-24,"6,908,716,120",9.6%,"35,226,317,690","674,629","3,349,683",817,"48,534",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
4,5,퍼스트 라이드,2025-10-29,"5,215,126,930",7.2%,"6,822,441,490","553,192","739,689","1,166","46,249",한국,한국,(주)쇼박스

In [165]:
df32.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
959,960,SIFF2025-페스티벌초이스 단편7,NaN,"-90,000",0.0%,"-90,000",-9,-9,1,1,한국,한국,NaN
960,961,다른 이름으로,NaN,"-110,000",0.0%,"890,000",-11,189,1,1,한국,한국,NaN
961,962,SIFF2025-페스티벌초이스 단편5,NaN,"-162,500",0.0%,"-162,500",-16,-16,1,1,한국,한국,NaN
962,963,전망세대,NaN,"-200,000",0.0%,"-200,000",-20,-20,1,1,일본,일본,NaN
963,964,마젤란,NaN,"-330,000",0.0%,"-330,000",-33,-33,1,1,포르투갈,"포르투갈,스페인,프랑스,필리핀,대만",NaN

In [166]:
df31["month"]="25.12"
df32["month"]="25.11"

In [167]:
df31.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df31.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,주토피아 2,2025-11-26,"53,971,262,890",38.5%,"74,124,615,600","5,598,839","7,705,705","2,282","180,184",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.12
1,2,아바타: 불과 재,2025-12-17,"52,409,899,290",37.4%,"52,409,899,290","4,569,538","4,569,538","2,582","102,298",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.12
2,3,윗집 사람들,2025-12-03,"5,186,086,360",3.7%,"5,284,239,800","537,349","546,584",768,"32,522",한국,한국,(주)바이포엠스튜디오,25.12
3,4,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",2025-12-24,"4,681,536,750",3.3%,"4,681,536,750","489,021","489,021",868,"15,093",한국,한국,(주)바이포엠스튜디오,25.12
4,5,극장판 주술회전: 시부야사변 X 사멸회유,2025-12-03,"3,628,196,350",2.6%,"3,648,294,490","357,977","359,636",756,"22,831",일본,일본,메가박스중앙(주),25.12

In [168]:
df32.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df32.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,주토피아 2,2025-11-26,"20,153,352,710",27.9%,"20,153,352,710","2,106,866","2,106,866","2,383","45,432",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.11
1,2,나우 유 씨 미 3,2025-11-12,"11,862,578,410",16.4%,"11,862,578,410","1,252,092","1,252,092","1,352","65,344",미국,미국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)바이포엠스튜디오",25.11
2,3,위키드: 포 굿,2025-11-19,"8,055,284,900",11.1%,"8,055,284,900","781,928","781,928","1,700","48,403",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),25.11
3,4,극장판 체인소 맨: 레제편,2025-09-24,"6,908,716,120",9.6%,"35,226,317,690","674,629","3,349,683",817,"48,534",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.11
4,5,퍼스트 라이드,2025-10-29,"5,215,126,930",7.2%,"6,822,441,490","553,192","739,689","1,166","46,249",한국,한국,(주)쇼박스,25.11

In [169]:
df = pd.concat([df32, df31])
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,주토피아 2,2025-11-26,"20,153,352,710",27.9%,"20,153,352,710","2,106,866","2,106,866","2,383","45,432",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.11
1,2,나우 유 씨 미 3,2025-11-12,"11,862,578,410",16.4%,"11,862,578,410","1,252,092","1,252,092","1,352","65,344",미국,미국,"롯데컬처웍스(주)롯데엔터테인먼트,(주)바이포엠스튜디오",25.11
2,3,위키드: 포 굿,2025-11-19,"8,055,284,900",11.1%,"8,055,284,900","781,928","781,928","1,700","48,403",미국,미국,유니버설픽쳐스인터내셔널 코리아(유),25.11
3,4,극장판 체인소 맨: 레제편,2025-09-24,"6,908,716,120",9.6%,"35,226,317,690","674,629","3,349,683",817,"48,534",일본,일본,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.11
4,5,퍼스트 라이드,2025-10-29,"5,215,126,930",7.2%,"6,822,441,490","553,192","739,689","1,166","46,249",한국,한국,(주)쇼박스,25.11

In [170]:
df.to_csv("251112.csv", index=False)

In [172]:
df=pd.read_csv("KOBIS_월별박스오피스_260102.csv")

In [176]:
df33 = df.iloc[7:621].reset_index(drop=True)
df33.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,왕과 사는 남자,2026-02-04,"73,493,037,620",62.0%,"73,742,894,090","7,641,781","7,667,180","2,165","179,807",한국,한국,(주)쇼박스
1,2,휴민트,2026-02-11,"17,802,011,580",15.0%,"17,818,289,580","1,766,508","1,767,510","1,520","74,117",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
2,3,신의악단,2025-12-31,"4,901,114,260",4.1%,"13,172,979,710","512,586","1,381,202",893,"26,420",한국,한국,씨제이 씨지브이(CJ CGV)(주)
3,4,만약에 우리,2025-12-31,"3,430,645,850",2.9%,"25,465,066,210","339,554","2,598,458",923,"26,127",한국,한국,(주)쇼박스
4,5,넘버원,2026-02-11,"2,523,309,980",2.1%,"2,530,164,980","263,905","264,607",652,"17,255",한국,한국,(주)바이포엠스튜디오

In [177]:
df33.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
609,594,달은...해가 꾸는 꿈,1992-02-29,0,0.0%,0,0,0,1,2,한국,한국,NaN
610,594,파고,1997-03-15,0,0.0%,0,0,0,1,1,미국,미국,NaN
611,594,8월의 크리스마스,1998-01-24,0,0.0%,0,0,0,1,2,한국,한국,"한국영상투자개발(주),(주)싸이더스"
612,594,죽거나 혹은 나쁘거나,2000-07-15,0,0.0%,0,0,0,1,2,한국,한국,(주)라이크콘텐츠
613,594,엄마를 버리러 갑니다,2025-11-05,0,0.0%,0,0,0,1,1,한국,"한국,베트남",(주)싸이더스

In [178]:
df34 = df.iloc[626:-1].reset_index(drop=True)
df34.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,만약에 우리,2025-12-31,"20,926,257,000",24.5%,"22,034,420,360","2,129,768","2,258,904","1,116","101,286",한국,한국,(주)쇼박스
1,2,아바타: 불과 재,2025-12-17,"25,385,921,530",29.7%,"77,795,820,820","2,085,863","6,655,401","1,761","89,685",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
2,3,주토피아 2,2025-11-26,"8,220,197,870",9.6%,"82,344,813,470","850,524","8,556,229",986,"45,464",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
3,4,신의악단,2025-12-31,"8,075,984,490",9.5%,"8,271,865,450","843,984","868,616",907,"39,027",한국,한국,씨제이 씨지브이(CJ CGV)(주)
4,5,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",2025-12-24,"3,651,424,140",4.3%,"8,332,960,890","370,974","859,995",743,"22,504",한국,한국,(주)바이포엠스튜디오

In [179]:
df34.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
648,467,감독의 딸들,2026-01-26,"1,000",0.0%,"1,000",1,1,1,1,일본,일본,(주)도키엔터테인먼트
649,650,황진이,1986-09-18,0,0.0%,"12,956,000",0,"6,241",1,2,한국,한국,NaN
650,650,돼지가 우물에 빠진 날,1996-05-15,0,0.0%,"606,000",0,95,1,2,한국,한국,NaN
651,650,왕십리,1976-01-31,0,0.0%,0,0,0,1,2,한국,한국,NaN
652,650,그대를 사랑합니다,2011-02-17,0,0.0%,"12,051,537,000",0,"1,649,429",1,1,한국,한국,(주)넥스트엔터테인먼트월드(NEW)

In [180]:
df33["month"]="26.02"
df34["month"]="26.01"

In [181]:
df33.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df33.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,왕과 사는 남자,2026-02-04,"73,493,037,620",62.0%,"73,742,894,090","7,641,781","7,667,180","2,165","179,807",한국,한국,(주)쇼박스,26.02
1,2,휴민트,2026-02-11,"17,802,011,580",15.0%,"17,818,289,580","1,766,508","1,767,510","1,520","74,117",한국,한국,(주)넥스트엔터테인먼트월드(NEW),26.02
2,3,신의악단,2025-12-31,"4,901,114,260",4.1%,"13,172,979,710","512,586","1,381,202",893,"26,420",한국,한국,씨제이 씨지브이(CJ CGV)(주),26.02
3,4,만약에 우리,2025-12-31,"3,430,645,850",2.9%,"25,465,066,210","339,554","2,598,458",923,"26,127",한국,한국,(주)쇼박스,26.02
4,5,넘버원,2026-02-11,"2,523,309,980",2.1%,"2,530,164,980","263,905","264,607",652,"17,255",한국,한국,(주)바이포엠스튜디오,26.02

In [182]:
df34.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df34.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,만약에 우리,2025-12-31,"20,926,257,000",24.5%,"22,034,420,360","2,129,768","2,258,904","1,116","101,286",한국,한국,(주)쇼박스,26.01
1,2,아바타: 불과 재,2025-12-17,"25,385,921,530",29.7%,"77,795,820,820","2,085,863","6,655,401","1,761","89,685",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,26.01
2,3,주토피아 2,2025-11-26,"8,220,197,870",9.6%,"82,344,813,470","850,524","8,556,229",986,"45,464",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,26.01
3,4,신의악단,2025-12-31,"8,075,984,490",9.5%,"8,271,865,450","843,984","868,616",907,"39,027",한국,한국,씨제이 씨지브이(CJ CGV)(주),26.01
4,5,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",2025-12-24,"3,651,424,140",4.3%,"8,332,960,890","370,974","859,995",743,"22,504",한국,한국,(주)바이포엠스튜디오,26.01

In [183]:
df = pd.concat([df34, df33])

In [184]:
df.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,만약에 우리,2025-12-31,"20,926,257,000",24.5%,"22,034,420,360","2,129,768","2,258,904","1,116","101,286",한국,한국,(주)쇼박스,26.01
1,2,아바타: 불과 재,2025-12-17,"25,385,921,530",29.7%,"77,795,820,820","2,085,863","6,655,401","1,761","89,685",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,26.01
2,3,주토피아 2,2025-11-26,"8,220,197,870",9.6%,"82,344,813,470","850,524","8,556,229",986,"45,464",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,26.01
3,4,신의악단,2025-12-31,"8,075,984,490",9.5%,"8,271,865,450","843,984","868,616",907,"39,027",한국,한국,씨제이 씨지브이(CJ CGV)(주),26.01
4,5,"오늘 밤, 세계에서 이 사랑이 사라진다 해도",2025-12-24,"3,651,424,140",4.3%,"8,332,960,890","370,974","859,995",743,"22,504",한국,한국,(주)바이포엠스튜디오,26.01

In [185]:
df.to_csv("260102.csv", index=False)

In [186]:
df=pd.read_csv("KOBIS_월별박스오피스_260304.csv")

In [190]:
df35 = df.iloc[7:717].reset_index(drop=True)
df35.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,살목지,2026-04-08,"22,831,804,120",34.0%,"22,940,186,820","2,227,421","2,238,031","1,511","105,553",한국,한국,(주)쇼박스
1,2,프로젝트 헤일메리,2026-03-18,"14,762,259,550",22.0%,"28,848,591,520","1,318,796","2,553,517","1,401","77,027",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
2,3,왕과 사는 남자,2026-02-04,"9,809,935,600",14.6%,"161,599,802,060","1,009,272","16,741,084","1,408","80,533",한국,한국,(주)쇼박스
3,4,악마는 프라다를 입는다 2,2026-04-29,"2,237,609,510",3.3%,"2,237,609,510","253,206","253,206","1,578","12,371",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
4,5,짱구,2026-04-22,"2,152,603,650",3.2%,"2,152,603,650","224,597","224,597",878,"13,994",한국,한국,(주)바이포엠스튜디오

In [191]:
df35.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
705,686,장가가는 길,NaN,0,0.0%,0,0,0,1,2,몽고,몽고,NaN
706,686,아버지,NaN,0,0.0%,0,0,0,1,2,몽고,몽고,NaN
707,686,시어머니,NaN,0,0.0%,0,0,0,1,2,몽고,몽고,NaN
708,686,비상 12.3,NaN,0,0.0%,0,0,0,1,2,한국,한국,NaN
709,686,뻐꾸기둥지위로 날아간 새,1977-09-17,0,0.0%,0,0,0,1,1,미국,미국,NaN

In [193]:
df36 = df.iloc[722:-1].reset_index(drop=True)
df36.head()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,1,왕과 사는 남자,2026-02-04,"78,046,972,370",68.4%,"151,789,866,460","8,064,632","15,731,812","2,262","230,629",한국,한국,(주)쇼박스
1,2,프로젝트 헤일메리,2026-03-18,"14,086,331,970",12.3%,"14,086,331,970","1,234,721","1,234,721","1,350","53,409",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점
2,3,호퍼스,2026-03-04,"7,017,060,940",6.2%,"7,027,671,940","711,999","712,810","1,013","42,868",미국,미국,월트디즈니컴퍼니코리아 유한책임회사
3,4,휴민트,2026-02-11,"2,177,210,730",1.9%,"19,995,500,310","213,864","1,981,374",784,"16,907",한국,한국,(주)넥스트엔터테인먼트월드(NEW)
4,5,삼악도,2026-03-11,"850,819,000",0.7%,"851,323,000","92,199","92,271",235,"7,543",한국,한국,TCO(주)더콘텐츠온

In [194]:
df36.tail()

,■ 월별 박스오피스,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
583,569,어네스트와 셀레스틴,2014-02-20,0,0.0%,"335,283,100",0,"49,823",1,1,프랑스,프랑스,씨너스엔터테인먼트(주)
584,569,12명의 성난 사람들,NaN,0,0.0%,"10,520,000",0,"4,075",1,1,미국,미국,NaN
585,569,허공에의 질주,NaN,0,0.0%,"5,151,000",0,711,1,1,미국,미국,NaN
586,569,플란다스의 개,2000-02-19,0,0.0%,"4,668,200",0,638,1,1,한국,한국,(주)시네마서비스
587,569,그들은 피아노 연주자를 쐈다,2025-01-29,0,0.0%,"29,985,900",0,"3,162",1,1,스페인,스페인,찬란

In [195]:
df35["month"]="25.04"
df36["month"]="25.03"

In [196]:
df35.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df35.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,살목지,2026-04-08,"22,831,804,120",34.0%,"22,940,186,820","2,227,421","2,238,031","1,511","105,553",한국,한국,(주)쇼박스,25.04
1,2,프로젝트 헤일메리,2026-03-18,"14,762,259,550",22.0%,"28,848,591,520","1,318,796","2,553,517","1,401","77,027",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.04
2,3,왕과 사는 남자,2026-02-04,"9,809,935,600",14.6%,"161,599,802,060","1,009,272","16,741,084","1,408","80,533",한국,한국,(주)쇼박스,25.04
3,4,악마는 프라다를 입는다 2,2026-04-29,"2,237,609,510",3.3%,"2,237,609,510","253,206","253,206","1,578","12,371",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.04
4,5,짱구,2026-04-22,"2,152,603,650",3.2%,"2,152,603,650","224,597","224,597",878,"13,994",한국,한국,(주)바이포엠스튜디오,25.04

In [197]:
df36.columns = [
    "ranking",
    "movie_name",
    "release_date",
    "sales",
    "sales_percentage",
    "cumulative_sales",
    "audience",
    "cumulative_audience",
    "screen_count",
    "show_count",
    "main_country",
    "country",
    "distributor", "month"
]
df36.head()

,ranking,movie_name,release_date,sales,sales_percentage,cumulative_sales,audience,cumulative_audience,screen_count,show_count,main_country,country,distributor,month
0,1,왕과 사는 남자,2026-02-04,"78,046,972,370",68.4%,"151,789,866,460","8,064,632","15,731,812","2,262","230,629",한국,한국,(주)쇼박스,25.03
1,2,프로젝트 헤일메리,2026-03-18,"14,086,331,970",12.3%,"14,086,331,970","1,234,721","1,234,721","1,350","53,409",미국,미국,소니픽쳐스엔터테인먼트코리아주식회사극장배급지점,25.03
2,3,호퍼스,2026-03-04,"7,017,060,940",6.2%,"7,027,671,940","711,999","712,810","1,013","42,868",미국,미국,월트디즈니컴퍼니코리아 유한책임회사,25.03
3,4,휴민트,2026-02-11,"2,177,210,730",1.9%,"19,995,500,310","213,864","1,981,374",784,"16,907",한국,한국,(주)넥스트엔터테인먼트월드(NEW),25.03
4,5,삼악도,2026-03-11,"850,819,000",0.7%,"851,323,000","92,199","92,271",235,"7,543",한국,한국,TCO(주)더콘텐츠온,25.03

In [198]:
df = pd.concat([df36, df35])

In [199]:
df.to_csv("260304.csv", index=False)